import json
R=[]
R.append({"developer":"AM Group","role":"contractor",
 "legal_entities":[{"name_hy":"«Էյ Էմ Գրուպ» ՍՊԸ","name_en":"AM Group LLC","tax_id":None,"form":"ՍՊԸ","registered_year":None,"source_url":"https://www.spyur.am/am/companies/am-group/38275/"}],
 "founded_year":None,"datalex_names":["ԷՅ ԷՄ ԳՐՈՒՊ","ԷՅԷՄ ԳՐՈՒՊ","ԱՄ ԳՐՈՒՊ"],"datalex_tax_id":None,
 "news_issues":[],"positives":[],"confidence":"low",
 "notes":"amgroup.am (phones 010 588424 / 093 588424 match input) belongs to «Էյ Էմ Գրուպ» ՍՊԸ, a manufacturer/installer of aluminium & metal-plastic windows, glass structures and alucobond facades, not a developer; the 5 'residential buildings' are most likely its facade/window works for other developers. The input email info@targetdevelopment.am belongs to Target Development («ԹԱՐԳԵԹ ԴԻՎԵԼՈՓՄԵՆՏ», td.am, Piazza Grande) - likely a data mix-up from the td.am source. Name 'AM Group' is generic (many unrelated AM Group entities exist); tax ID not found. Verify by address/tax ID before matching court records."})
R.append({"developer":"Best Land","role":"developer",
 "legal_entities":[{"name_hy":"«Կապիտալ Բիլդ» ՍՊԸ","name_en":"Capital Build LLC","tax_id":None,"form":"ՍՊԸ","registered_year":2018,"source_url":"https://www.e-register.am/am/companies/1245574/declaration/e68aa566-5718-4a72-be8e-6ac8f98e73c3"},
                   {"name_hy":"«Երևանի լուսատեխնիկ» ԲԲԸ","name_en":"Yerevan Lusatekhnik OJSC","tax_id":None,"form":"ԲԲԸ","registered_year":1995,"source_url":"https://www.capitalbuild.am/storage/files/kapital-bild-spy-hamakhmbvats-hashvetvvouthyvoun.pdf"}],
 "founded_year":2018,"datalex_names":["ԿԱՊԻՏԱԼ ԲԻԼԴ","ԵՐԵՎԱՆԻ ԼՈՒՍԱՏԵԽՆԻԿ"],"datalex_tax_id":None,
 "news_issues":[
  {"date":"2020-05-06","title":"Ինչի դիմաց է «Կապիտալ Բիլդ» ՍՊԸ-ն Երևանին 100 մլն դրամանոց փոշեկուլներ նվիրել","url":"https://factor.am/247533.html","summary":"Factor.am questions Capital Build's donations of street-sweeper vehicles (AMD 100m) to Yerevan municipality shortly after it received land at Komitas 19/1 for construction; implies possible quid-pro-quo (no charges reported)."},
  {"date":"2022-09-07","title":"Цахкадзорские билдинги, или «300 процентов прибыли»","url":"https://nv.am/czahkadzorskie-bildingi-ili-300-proczentov-pribyli/","summary":"Golos Armenii criticises Capital Build's large resort/cottage construction in the Tandzakhpyur gorge near Kecharis monastery in Tsaghkadzor as damaging landscape and heritage surroundings."},
  {"date":"2024-08-27","title":"Tzaghkadzor: High-Rise Building Boom Threatens Armenian Resort Town","url":"https://hetq.am/en/article/168968","summary":"Hetq lists Capital Build among 14 companies given permits by the Tsaghkadzor mayor for multi-storey residential complexes after zoning changes; critical of the building boom."}],
 "positives":[{"title":"ТОП-10 крупнейших застройщиков Армении (No.1 Capital Build)","url":"https://xn--b1agapfwapgcl.xn--p1ai/mirovoj-development-top-10-krupnejshih-zastrojshhikov-armenii/","summary":"Russian construction portal ranks Capital Build first among Armenia's largest developers (2024)."},
              {"title":"Capital Build project portfolio","url":"https://www.capitalbuild.am/","summary":"Large portfolio: Komitas 59 multifunctional complex, Komitas 19/1, Davtashen, A. Khachatryan 3, Arshakunyats Residence, Avenue 22, Malibu Park, Blue/White Sky Residence, Tsaghkadzor projects, Bestland (Dzoraghbyur)."}],
 "confidence":"high",
 "notes":"'Best Land' (Bestland Residence, 70 houses in Greenland district, Dzoraghbyur) is a Capital Build project per capitalbuild.am and input website/phones. e-register BO declaration: «ԿԱՊԻՏԱԼ ԲԻԼԴ» ՍՊԸ, reg. no. 264.110.1018618 dated 21/05/2018; beneficial owners Eduard Gasparyan, Vahan Avagyan, Karen Gasparyan. Director Arman Gundakchyan (spyur). Consolidated 2021 FS shows subsidiary «Երևանի լուսատեխնիկ» ԲԲԸ (reg. 264.120.01401), which holds the Komitas 59 building permit. Tax ID not found in public sources checked (minfin lists, construction.am, spyur)."})
R.append({"developer":"4A Capital","role":"developer",
 "legal_entities":[{"name_hy":"«4Ա Կապիտալ» ՍՊԸ","name_en":"4A Capital LLC","tax_id":"00239045","form":"ՍՊԸ","registered_year":2021,"source_url":"https://www.construction.am/companies/4a-capital/"}],
 "founded_year":2021,"datalex_names":["4Ա ԿԱՊԻՏԱԼ","ՖՈՐ ԷՅ ԿԱՊԻՏԱԼ","4A ԿԱՊԻՏԱԼ"],"datalex_tax_id":"00239045",
 "news_issues":[
  {"date":"2024-08-27","title":"Tzaghkadzor: High-Rise Building Boom Threatens Armenian Resort Town","url":"https://hetq.am/en/article/168968","summary":"Hetq names 4A Capital among 14 companies permitted to build multi-storey residential complexes in Tsaghkadzor after a 2022 zoning relaxation; critical coverage of the boom (no violation alleged specifically)."},
  {"date":"2024-09-25","title":"Цахкадзор, который мы потеряли","url":"https://nv.am/czahkadzor-kotoryj-my-poteryali/","summary":"Golos Armenii lists 4A Capital among LLCs given permits for up-to-10-storey complexes in Tsaghkadzor; critical of zoning changes."}],
 "positives":[{"title":"Accor to open new Mövenpick hotel in Armenia","url":"https://hospitalitynet.org/announcement/41011459.html","summary":"Accor signed a management agreement with 4A Capital LLC (owner Davit Sokhakyan) for the 198-room Mövenpick Resort Tsaghkadzor, opening 2026."},
              {"title":"В Армении откроется отель Mövenpick","url":"https://banks.am/ru/news/newsfeed/28106","summary":"Coverage of the Accor/4A Capital hotel deal."}],
 "confidence":"high",
 "notes":"construction.am lists \"4A Capital\" LLC, TIN 00239045, head Davit Sokhakyan, Azatutyan Ave 12/2, since 2021. Projects: City View, Aivazovsky RC (Arabkir), Nest Residence, Mövenpick Resort Tsaghkadzor. Sales/management handled by City Nest (citynest.am, which also markets Renco's Milano/Firenze Towers). Armenian spelling with digit '4Ա' unverified in registry; datalex may store it as '4Ա ԿԱՊԻՏԱԼ' - search also by TIN."})
R.append({"developer":"Renshin Urban Investments","role":"developer",
 "legal_entities":[{"name_hy":"«Ռենշին» ՍՊԸ","name_en":"Renshin LLC","tax_id":"02564558","form":"ՍՊԸ","registered_year":2002,"source_url":"https://www.construction.am/companies/renshin-llc/"}],
 "founded_year":2002,"datalex_names":["ՌԵՆՇԻՆ"],"datalex_tax_id":"02564558",
 "news_issues":[
  {"date":"2023-09-07","title":"Здание ереванского Главпочтамта будет отчуждено в пользу компании «Реншин»","url":"https://rus.azatutyun.am/a/32582550.html","summary":"Government declared overriding public interest to expropriate the Soviet-era Main Post Office building on Saryan St. in favour of Renshin for a World Trade Center; contested as expropriation for a private investor."}],
 "positives":[
  {"title":"Проект из Армении удостоен высшей награды на International Property Awards","url":"https://armenpress.am/ru/article/1100566","summary":"Armenian project (Renshin) won top prize at International Property Awards (Dec 2022)."},
  {"title":"Компания «Реншин» впервые выпустила облигации: андеррайтером выступает Америабанк","url":"https://newsarmenia.am/news/economy/kompaniya-renshin-vpervye-vypustila-obligatsii-anderrayterom-vystupaet-ameriabank/","summary":"Feb 2026: first AMD 10bn bond issue underwritten by Ameriabank."},
  {"title":"Аудит компании «Реншин» со стороны KPMG","url":"https://armbanks.am/2026/04/15/272233/","summary":"KPMG audit of Renshin financial statements."},
  {"title":"Renshin and GTB are uniting around the Cascade project","url":"https://armbanks.am/en/2026/07/03/275768/","summary":"July 2026 strategic deal with GTB on completing the Cascade complex."},
  {"title":"Agreement signed on construction of World Trade Center in Yerevan","url":"https://arka.am/en/","summary":"Apr 2024 tripartite agreement for a USD 250m WTC; Colliers hired as project manager (Hetq, Oct 2024). Also Artlife Kempinski Residences and Skyline quarter."}],
 "confidence":"high",
 "notes":"construction.am: \"Renshin\" LLC, TIN 02564558, address 91 Pavstos Buzand St; same TIN in Ministry of Finance large/medium entity list (minfin.am List.pdf, «ՌԵՆՇԻՆ»). Owners reported as Araik Karapetyan and Eduard Marutyan (banks.am 2017). Brands: Renshin Urban Investments, Artlife/Kempinski Residences, Skyline, WTC Yerevan. Project-specific SPVs may exist but not identified."})
json.dump(R,open('research_2.json','w'),ensure_ascii=False,indent=1)
print(len(R))

def D(name): return next(r for r in R if r["developer"]==name)
cb=D("Best Land")
cb["news_issues"].append({"date":"2026-07-03","title":"«Շինարարության զոհերից մեկն ենք դառնում». Անաստաս Միկոյան 2/2-ի բնակիչները կվիճարկեն շինթույլտվության օրինականությունը","url":"https://www.azatutyun.am/a/shinararoutyan-zoherits-mekn-enk-darnoum-anastas-mikoyan-2-2-i-bnakichnery-kvicharken-shintouyltvoutyan-%D6%85rinakanoutyouny/33795715.html","summary":"Residents of Anastas Mikoyan 2/2 (Davtashen), incl. ex-Justice Minister Arpine Hovhannisyan, plan to challenge the legality of the building permit for Capital Build's new construction next to their building."})
rs=D("Renshin Urban Investments")
rs["positives"][-1]={"title":"Agreement signed on construction of World Trade Center in Yerevan","url":"https://arka.am/en/news/economy/_agreement_signed_on_construction_of_world_trade_center_in_yerevan_/","summary":"Apr 2024 tripartite agreement for WTC Yerevan on the former Haypost site; Colliers hired as project manager for the USD 250m project (https://www.hetq.am/en/article/170342)."}
rs["news_issues"]+=[
 {"date":"2021-12-30","title":"Նվիրատվությանը նախորդած կամ հաջորդած շինթույլտվությունների տրամադրումը դասական կոռուպցիա է. փորձագետ","url":"https://www.azatutyun.am/a/31633407.html","summary":"Azatutyun: Renshin among companies that donated property to Yerevan municipality around the time of receiving construction permits; an expert calls such patterns classic corruption (no charges reported)."},
 {"date":"2024-02-28","title":"«Բայց ինչո՞ւ մենք պետք է վճարենք». կոնդեցիները թաղամասի օտարմանն առնչվող դժգոհություններ ունեն","url":"https://www.azatutyun.am/a/32840558.html","summary":"Kond residents' grievances over district expropriation; mentions sale of the Haypost building behind Kond to Renshin."},
 {"date":"2024-09-23","title":"Երևանի թիվ 172 դպրոցում դասերը հեռավար են. ի՞նչ կապ կա հարակից շինարարության ու դպրոցում նկատված ցնցումների միջև","url":"https://www.azatutyun.am/a/erevani-tiv-172-dprotsoum-dasery-heravar-en/33131090.html","summary":"School No.172 evacuated and moved to remote classes after vibrations were felt; parents blame adjacent Renshin construction of the 5x35-storey Skyline complex (Baghramyan-Orbeli); geotechnical report found no link."}]
R+= [
{"developer":"Seray Homes (Seray Developments)","role":"developer",
 "legal_entities":[{"name_hy":"«Սէրայ Հոմզ» ՍՊԸ","name_en":"Seray Homes LLC","tax_id":None,"form":"ՍՊԸ","registered_year":2018,"source_url":"https://www.spyur.am/am/companies/seray-homes/48852"}],
 "founded_year":2018,"datalex_names":["ՍԷՐԱՅ ՀՈՄԶ","ՍԵՐԱՅ ՀՈՄԶ","ՍԵՐԱՅ ՀՈՈՒՄՍ"],"datalex_tax_id":None,
 "news_issues":[],"positives":[],"confidence":"medium",
 "notes":"Seray Developments is a Lebanese group (est. Lebanon; Cyprus 2017) that 'entered the Armenian market with Seray Homes Ltd' in 2018 (seraydevelopments.com); Yerevan office Orbelyan 12. Spyur lists «ՍԷՐԱՅ ՀՈՄԶ» ՍՊԸ (Latin SERAY HOMZ) with status 'ՉԻ ԳՈՐԾՈՒՄ' (not operating) as of Jan 2026 - worth checking given Otevan 2/4 are still 'future' projects. Otevan projects may use separate SPVs (not identified). No news found."},
{"developer":"Defanse Housing Invest","role":"developer",
 "legal_entities":[{"name_hy":"«Դեֆանս Հաուզինգ Ինվեստ» ՓԲԸ","name_en":"Defanse Housing Invest CJSC","tax_id":"00449838","form":"ՓԲԸ","registered_year":None,"source_url":"https://minfin.am/website/images/website/2023_list%20(1).pdf"}],
 "founded_year":2022,"datalex_names":["ԴԵՖԱՆՍ ՀԱՈՒԶԻՆԳ ԻՆՎԵՍՏ","ԴԵՖԱՆՍ ՀԱՈՒԶԻՆԳ"],"datalex_tax_id":"00449838",
 "news_issues":[],
 "positives":[{"title":"Defanse Housing Invest company profile","url":"https://www.construction.am/companies/defanse-housing-invest/","summary":"CJSC building the 140-ha 'Defanse Housing' multifunctional district at Tichina 320 near the North-South highway, with a 24-ha forest park; self-described largest developer in Armenia."}],
 "confidence":"high",
 "notes":"construction.am describes \"Defanse Housing Invest\" CJSC (since 2022 on the portal); Ministry of Finance 2023 list of large/medium entities gives «ԴԵՖԱՆՍ ՀԱՈՒԶԻՆԳ ԻՆՎԵՍՏ», TIN 00449838 (low TIN suggests an older entity, possibly renamed). Head office Hyusisayin Ave 8/8. Only tangential press found (Azatutyun 2024 piece on Haghtanak residents mentioning 'Defanse' building 50 m from their plots: https://www.azatutyun.am/a/33309950.html)."},
{"developer":"ADA Tech","role":"developer",
 "legal_entities":[{"name_hy":"«Էյ Դի Էյ Թեք» ՍՊԸ","name_en":"ADA Tech LLC","tax_id":"00870486","form":"ՍՊԸ","registered_year":2010,"source_url":"https://www.spyur.am/am/companies/ada-tech/29509"}],
 "founded_year":2010,"datalex_names":["ԷՅ ԴԻ ԷՅ ԹԵՔ","ԷՅԴԻԷՅ ԹԵՔ","ԱԴԱ ԹԵՔ"],"datalex_tax_id":"00870486",
 "news_issues":[],
 "positives":[{"title":"ADA Tech company profile","url":"https://www.construction.am/companies/ada-tech-llc/","summary":"Capital construction contractor/developer founded 2010, 251-1000 employees (spyur), claims to be among the 10 largest construction firms in Armenia; also produces ready-mix concrete."}],
 "confidence":"high",
 "notes":"spyur: «ԷՅ ԴԻ ԷՅ ԹԵՔ» ՍՊԸ, director Rafik H. Ghazaryan, Tsarav Aghbyur 55/5; TIN 00870486 from Ministry of Finance large/medium entities list («ԷՅ ԴԻ ԷՅ ԹԵՔ»). Primarily a general contractor; developer for Sarkavag 42/15. No news found."},
{"developer":"Piazza Grande","role":"developer",
 "legal_entities":[{"name_hy":"«Թարգեթ Դիվելոփմենտ» ՍՊԸ","name_en":"Target Development LLC","tax_id":None,"form":"ՍՊԸ","registered_year":2010,"source_url":"https://www.spyur.am/en/companies/target-development/7271/"},
                   {"name_hy":"«Ռենկո Արմէստեյտ» ՍՊԸ","name_en":"Renco ArmEstate LLC","tax_id":"02560091","form":"ՍՊԸ","registered_year":2001,"source_url":"https://www.spyur.am/am/companies/renco-armestate/2840"}],
 "founded_year":2007,"datalex_names":["ԹԱՐԳԵԹ ԴԻՎԵԼՈՓՄԵՆՏ","ՊԻԱՑՑԱ ԳՌԱՆԴԵ","ՌԵՆԿՈ ԱՐՄԷՍՏԵՅՏ"],"datalex_tax_id":None,
 "news_issues":[],
 "positives":[{"title":"Компания RENCO сдала в эксплуатацию в Ереване торгово-жилой комплекс Piazza Grande стоимостью в $50 млн.","url":"https://newsarmenia.am/news/politics/arm1-20100920-42311694/","summary":"Sept 2010: Italian RENCO commissioned the USD 50m Piazza Grande mixed-use complex at Vazgen Sargsyan 10 near Republic Square."}],
 "confidence":"medium",
 "notes":"Piazza Grande (Vazgen Sargsyan 10) is a completed 2010 Class-A mixed-use building constructed by RENCO; it is managed/marketed by Target Development («ԹԱՐԳԵԹ ԴԻՎԵԼՈՓՄԵՆՏ», td.am, offices in the building; input email info@targetdevelopment.am). Spyur also lists a separate brand record «ՊԻԱՑՑԱ ԳՌԱՆԴԵ» multifunctional centre (founded 2007). Which entity holds title is unclear - Renco ArmEstate shares the same address. Aug 2026 press reported law-enforcement searches in offices inside the Piazza Grande business centre in connection with the Kocharyan case (tenant office, not the developer): https://golosarmenii.am/%D0%9F%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B8-%D0%BF%D1%80%D0%BE%D0%B2%D0%BE%D0%B4%D1%8F%D1%82%D1%81%D1%8F-%D0%B2-%D0%B1%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D1%86%D0%B5%D0%BD%D1%82%D1%80%D0%B5-piazza-gr/ . Target Development tax ID not found."},
{"developer":"Ecoshin Group","role":"developer",
 "legal_entities":[{"name_hy":"«Էկոշին Գրուպ» ՍՊԸ","name_en":"Ecoshin Group LLC","tax_id":"01274214","form":"ՍՊԸ","registered_year":2017,"source_url":"https://www.construction.am/companies/ecoshin-group/"}],
 "founded_year":2017,"datalex_names":["ԷԿՈՇԻՆ ԳՐՈՒՊ","ԷԿՕՇԻՆ ԳՐՈՒՊ","ԷԿՈ ՇԻՆ"],"datalex_tax_id":"01274214",
 "news_issues":[],"positives":[],"confidence":"high",
 "notes":"construction.am: \"Ecoshin Group\" LLC, TIN 01274214, head Vardan Manukyan, 67/2 Orbeli Brothers St; same TIN in Ministry of Finance large/medium entity list («ԷԿՈՇԻՆ ԳՐՈՒՊ»). Spyur founding year 2017. Also developer of Greenwood Residence (same email/website). No news found."},
{"developer":"Monument Hills","role":"developer",
 "legal_entities":[{"name_hy":"«Մոնումենտ Հիլզ» ՍՊԸ","name_en":"Monument Hills LLC","tax_id":None,"form":"ՍՊԸ","registered_year":None,"source_url":"https://monumenthills.am/info"}],
 "founded_year":None,"datalex_names":["ՄՈՆՈՒՄԵՆՏ ՀԻԼԶ","ՄՈՆՈՒՄԵՆՏ ՀԻԼՍ","ՄՈՆՈՒՄԵՆԹ ՀԻԼԶ"],"datalex_tax_id":None,
 "news_issues":[],"positives":[{"title":"Monument Hills partner bank","url":"https://monumenthills.am/info","summary":"Inecobank CJSC listed as partner bank for mortgages."}],
 "confidence":"medium",
 "notes":"Armenian site footer: '© «ՄՈՆՈՒՄԵՆՏ ՀԻԼԶ» ՍՊԸ 2022'; project at Davit Anhaght 6 (Kanaker-Zeytun), spyur lists it as residential complex brand. The English footer instead shows '\"Go Web\" LLC' (likely template/web developer artefact). Tax ID not found; no news found."},
{"developer":"Greenwood Residence","role":"developer",
 "legal_entities":[{"name_hy":"«Էկոշին Գրուպ» ՍՊԸ","name_en":"Ecoshin Group LLC","tax_id":"01274214","form":"ՍՊԸ","registered_year":2017,"source_url":"https://www.construction.am/companies/ecoshin-group/"}],
 "founded_year":2017,"datalex_names":["ԷԿՈՇԻՆ ԳՐՈՒՊ","ԳՐԻՆՎՈՒԴ ՌԵԶԻԴԵՆՍ"],"datalex_tax_id":"01274214",
 "news_issues":[],"positives":[],"confidence":"medium",
 "notes":"Greenwood Residence is a project brand; input website ecoshingroup.am and email info@ecoshingroup.am (phone 011 611100 matches Ecoshin's 055 611100 pattern) point to Ecoshin Group LLC (TIN 01274214). A project-specific SPV was not found. Duplicate of 'Ecoshin Group' entity."},
{"developer":"IVY Garden  (PJKT Development)","role":"developer",
 "legal_entities":[{"name_hy":"«Այվի Գարդեն» ՍՊԸ","name_en":"IVY Garden LLC","tax_id":None,"form":"ՍՊԸ","registered_year":None,"source_url":"https://www.ivygarden.am/_files/ugd/cf0b6c_bb73c6c11e8049c3b66ab202ac0ade01.pdf"}],
 "founded_year":None,"datalex_names":["ԱՅՎԻ ԳԱՐԴԵՆ","ՓԻ ՋԵՅ ՔԵՅ ԹԻ ԴԵՎԵԼՈՓՄԵՆԹ","ԻՎԻ ԳԱՐԴԵՆ"],"datalex_tax_id":None,
 "news_issues":[],"positives":[],"confidence":"medium",
 "notes":"Public reservation offer PDF on ivygarden.am names the offeror/seller as «Այվի Գարդեն» ՍՊԸ (account at Ameriabank); site footer '© IVY GARDEN LLC'; 'Property developer: PJKT Development' is a brand/sponsor whose Armenian registration was not found. Project at Armenakyan 108/7. No news found."},
{"developer":"Renco ArmEstate (Nuovo Velodromo)","role":"developer",
 "legal_entities":[{"name_hy":"«Ռենկո Արմէստեյտ» ՍՊԸ","name_en":"Renco ArmEstate LLC","tax_id":"02560091","form":"ՍՊԸ","registered_year":2001,"source_url":"https://www.spyur.am/am/companies/renco-armestate/2840"},
                   {"name_hy":"«Ռենկո Ս.Պ.Ա» բաժնետիրական ընկերության մասնաճյուղ","name_en":"RENCO S.p.A. Armenian branch","tax_id":"02546651","form":"մասնաճյուղ","registered_year":None,"source_url":"https://www.minfin.am/website/images/website/List.pdf"}],
 "founded_year":2001,"datalex_names":["ՌԵՆԿՈ ԱՐՄԷՍՏԵՅՏ","ՌԵՆԿՈ ԱՐՄԵՍՏԵՅՏ","ՌԵՆԿՈ"],"datalex_tax_id":"02560091",
 "news_issues":[],
 "positives":[{"title":"Apartments and commercial spaces: Another major project by the Italian company RENCO","url":"https://news.am/en/news/883506","summary":"May 2025: RENCO announces Milano and Firenze Towers residential/commercial project (Nuovo Velodromo)."},
              {"title":"Компания RENCO сдала в эксплуатацию в Ереване торгово-жилой комплекс Piazza Grande","url":"https://newsarmenia.am/news/politics/arm1-20100920-42311694/","summary":"Long track record in Armenia: Piazza Grande (2010), DoubleTree by Hilton, Yerevan 250 MW gas power plant, velodrome."}],
 "confidence":"high",
 "notes":"Spyur: «ՌԵՆԿՈ ԱՐՄԷՍՏԵՅՏ» ՍՊԸ, director Paolo Paffumi, Vazgen Sargsyan 10, founded 2001, partners RENCO S.p.A./RENCO Group; phone 010 590799 and armestate@renco.it match input. TIN 02560091 from Ministry of Finance large/medium entity list; RENCO S.p.A. branch TIN 02546651. Sales via City Nest (citynest.am lists Milano Firenze Towers, G. Lusavorich 4, completion Dec 2028)."},
{"developer":"Deka (Deka 10 )","role":"developer",
 "legal_entities":[{"name_hy":"«Դեկա 10» ՍՊԸ","name_en":"Deka 10 LLC","tax_id":None,"form":"ՍՊԸ","registered_year":None,"source_url":"https://www.spyur.am/am/companies/deka-10-construction-organization/50698"}],
 "founded_year":2021,"datalex_names":["ԴԵԿԱ 10","ԴԵԿԱ ՏԱՍԸ","ԴԵԿԱ"],"datalex_tax_id":None,
 "news_issues":[],"positives":[],"confidence":"medium",
 "notes":"deka.am footer '© 2021-2026 \"Deka 10\" LLC', construction licence ՔՊԼ N 18197, Davtashen 2nd district 45; spyur: «ԴԵԿԱ 10» ՇԻՆԱՐԱՐԱԿԱՆ ԿԱԶՄԱԿԵՐՊՈՒԹՅՈՒՆ ՍՊԸ (keyword alias «ԴԵԿԱ»). Byurakan Resort not started. Name 'Deka' collides with unrelated entities (e.g. «ԴԵԿԱ» welding materials factory) - match on '10' or tax ID. No news found."},
{"developer":"Amikson Sapphire  (sales: RED Invest Group)","role":"developer",
 "legal_entities":[{"name_hy":"«Ամիկսոն Սապֆիր» ՍՊԸ","name_en":"Amikson Sapphire LLC","tax_id":None,"form":"ՍՊԸ","registered_year":None,"source_url":"https://www.redinvest.am/developers/334"}],
 "founded_year":None,"datalex_names":["ԱՄԻԿՍՈՆ ՍԱՊՖԻՐ","ԱՄԻՔՍՈՆ ՍԱՊՖԻՐ","ԱՄԻԿՍՈՆ"],"datalex_tax_id":None,
 "news_issues":[],"positives":[],"confidence":"medium",
 "notes":"RED Invest project page (Sapphire multifunctional complex, A. Harutyunyan 1, Nor Hachn; 'train with Juventus' academy tie-in): developer «Ամիկսոն Սապֆիր» ՍՊԸ, builder «Ազուրիտ» ՍՊԸ, partner bank Unibank; Building 2 started 06/2023 due end-Oct 2026, Building 1 starts 11/2026 due 05/2029 (long timeline - monitor). Exclusive sales «ՌԷԴ Ինվեսթ Գրուպ» ՍՊԸ (\"Red Group\" LLC, TIN 03316198). Tax ID not found; no news found."},
{"developer":"Modern Construction (sales: RED Invest Group)","role":"developer",
 "legal_entities":[{"name_hy":"«Մոդերն Քընսթրաքշն» ՍՊԸ","name_en":"Modern Construction LLC","tax_id":None,"form":"ՍՊԸ","registered_year":None,"source_url":"https://www.redinvest.am/developers/305"}],
 "founded_year":None,"datalex_names":["ՄՈԴԵՐՆ ՔԸՆՍԹՐԱՔՇՆ","ՄՈԴԵՌՆ ՔՈՆՍԹՐԱՔՇՆ","ՄՈԴԵՌՆ ԿՈՆՍՏՐՈՒԿՑԻԱ"],"datalex_tax_id":None,
 "news_issues":[],"positives":[],"confidence":"medium",
 "notes":"RED Invest project page for Novotel investment property (Saralanj 1st St. 5, Tsaghkadzor; completion 12/2026): 'Project manager and developer «Մոդերն Քընսթրաքշն» ՍՊԸ', designer «Ա41 Պրոջեկտ» ՍՊԸ. Generic name - many similarly named entities likely; verify by tax ID. Possibly related to 'Modern Structure' listed by Hetq among Tsaghkadzor permit holders (unconfirmed). No news found."},
{"developer":"House Construction  (sales: RED Invest Group)","role":"developer",
 "legal_entities":[{"name_hy":"«Հաուս Քոնսթրաքշն» ՍՊԸ","name_en":"House Construction LLC","tax_id":None,"form":"ՍՊԸ","registered_year":None,"source_url":"https://www.redinvest.am/developers/411"}],
 "founded_year":None,"datalex_names":["ՀԱՈՒՍ ՔՈՆՍԹՐԱՔՇՆ","ՀԱՈՒՍ ՔԸՆՍԹՐԱՔՇՆ","ՀԱՈՒՍ ԿՈՆՍՏՐՈՒԿՑԻԱ"],"datalex_tax_id":None,
 "news_issues":[],"positives":[],"confidence":"medium",
 "notes":"RED Invest North Yard page (Yeghvard, Kotayk): developer «Հաուս Քոնսթրաքշն» ՍՊԸ, architect «Թի Էֆ + Արքիթեքթս» ՍՊԸ, builder «Arm Construct» ՍՊԸ (see ARM Construct, TIN 02688892 - possibly related), partner bank Ameriabank; construction 2025 to Dec 2026. Tax ID not found; no news found."},
{"developer":"Life House  (sales: RED Invest Group)","role":"developer",
 "legal_entities":[{"name_hy":"«Լայֆ Հաուս» ՍՊԸ","name_en":"Life House LLC","tax_id":None,"form":"ՍՊԸ","registered_year":None,"source_url":"https://www.redinvest.am/developers/405"}],
 "founded_year":None,"datalex_names":["ԼԱՅՖ ՀԱՈՒՍ"],"datalex_tax_id":None,
 "news_issues":[],"positives":[],"confidence":"medium",
 "notes":"RED Invest Life House page (private houses, Merdzavan village, Armavir): developer Լայֆ Հաուս ՍՊԸ, designer «ՊՐՈՖԷՆԵՐՋԻ ԳՐՈՒՊ» ՍՊԸ, partner bank Armeconombank; construction planned Sep 2026 - Dec 2027. Generic name; verify by tax ID. No news found."},
{"developer":"Slavonic Residence (sales: RED Invest Group)","role":"developer",
 "legal_entities":[{"name_hy":"«Սլավոնական Ռեզիդենս» ՍՊԸ","name_en":"Slavonic Residence LLC","tax_id":None,"form":"ՍՊԸ","registered_year":None,"source_url":"https://www.redinvest.am/developers/367"}],
 "founded_year":None,"datalex_names":["ՍԼԱՎՈՆԱԿԱՆ ՌԵԶԻԴԵՆՍ","ՍԼԱՎՈՆԻԿ ՌԵԶԻԴԵՆՍ"],"datalex_tax_id":None,
 "news_issues":[],"positives":[],"confidence":"medium",
 "notes":"RED Invest page ('Slavonakan' Residence, Hovsep Emin 128-130): developer «Սլավոնական Ռեզիդենս» ՍՊԸ, designer «ՊՐՈՖԷՆԵՐՋԻ ԳՐՈՒՊ» ՍՊԸ, contractor «ՀՈՎՍԵՓՅԱՆ-90 ՇԻՆ» ՍՊԸ; started Jan 2024, completion due 1H 2026 (still listed in progress in input - possible delay). Tax ID not found; no news found."},
{"developer":"My Home realty (sales: RED Invest Group)","role":"developer",
 "legal_entities":[{"name_hy":"«Մայ Հոմ Ռիելթի» ՓԲԸ","name_en":"My Home Realty CJSC","tax_id":None,"form":"ՓԲԸ","registered_year":None,"source_url":"https://www.redinvest.am/developers/260"}],
 "founded_year":None,"datalex_names":["ՄԱՅ ՀՈՄ ՌԻԵԼԹԻ","ՄԱՅ ՀՈՈՒՄ ՌԻԵԼԹԻ","ՄԱՅ ՀՈՄ ՌԻԼԹԻ"],"datalex_tax_id":None,
 "news_issues":[],"positives":[],"confidence":"medium",
 "notes":"RED Invest West Town residential district page: developer «Մայ Հոմ Ռիելթի» ՓԲԸ; construction 09/2021-08/2022 (completed). Armenian page names builder «Մալխասյան Շին» ՍՊԸ while the English page says 'T-construction' CJSC; partner banks Evocabank (hy) / ID Bank (en). Tax ID not found; no news found."},
{"developer":"Step Construction","role":"developer",
 "legal_entities":[{"name_hy":"«Ստեփ Քոնսթրաքշն» ՍՊԸ","name_en":"Step Construction LLC","tax_id":None,"form":"ՍՊԸ","registered_year":2022,"source_url":"https://www.spyur.am/am/companies/step-construction-construction-company/52633"}],
 "founded_year":2022,"datalex_names":["ՍՏԵՓ ՔՈՆՍԹՐԱՔՇՆ","ՍԹԵՓ ՔՈՆՍԹՐԱՔՇՆ","ՍՏԵՓ ԴԵՎԵԼՈՓՄԵՆԹ"],"datalex_tax_id":None,
 "news_issues":[],"positives":[],"confidence":"medium",
 "notes":"Spyur: «ՍՏԵՓ ՔՈՆՍԹՐԱՔՇՆ» ՇԻՆԱՐԱՐԱԿԱՆ ԸՆԿԵՐՈՒԹՅՈՒՆ (alias «ՍՏԵՓ ԴԵՎԵԼՈՓՄԵՆԹ»), Gevorg Chaush 11/5, site/phone match input; on construction.am since 2022. Small design-build firm (townhouses in Bagrevand/Duryan, private houses in Mush district); appears as a source for Deka projects (possibly contractor). Legal form assumed ՍՊԸ; tax ID not found; no news found."},
{"developer":"ARM Construct","role":"developer",
 "legal_entities":[{"name_hy":"«Արմ Կոնստրակտ» ՍՊԸ","name_en":"Arm Construct LLC","tax_id":"02688892","form":"ՍՊԸ","registered_year":2019,"source_url":"https://www.construction.am/companies/arm-construct/"}],
 "founded_year":2019,"datalex_names":["ԱՐՄ ԿՈՆՍՏՐԱԿՏ","ԱՐՄ ՔՈՆՍԹՐԱՔԹ","ԱՐՄ ՔՈՆՍԹՐԱՔՇՆ"],"datalex_tax_id":"02688892",
 "news_issues":[],
 "positives":[{"title":"ArmConstruct projects","url":"https://armconstruct.am/","summary":"Portfolio: Five Towers (Gevorg Chaush 95), Atlantis Prime and Atlantis Yerevan (Malkhasyants lane), Komitas 60/3, Slavik Chiloyan 17; also general contractor for North Yard (House Construction LLC)."}],
 "confidence":"high",
 "notes":"construction.am: \"Arm Construct\" LLC, TIN 02688892, Slavik Chiloyan 17 (site says company created 2019; construction.am 'since 2018'). Spyur: «ԱՐՄ ԿՈՆՍՏՐԱԿՏ» ԿԱՌՈՒՑԱՊԱՏՈՂ ԸՆԿԵՐՈՒԹՅՈՒՆ, director Aram Avagyan, keyword alias «ԱՐՄ ՔՈՆՍԹՐԱՔԹ» - registered spelling uncertain, search both. No news found."}]
json.dump(R,open('research_2.json','w'),ensure_ascii=False,indent=1)
print(len(R),[r['developer'] for r in R])
