import json
ER="https://www.e-register.am/hy/search/companies?query="
import urllib.parse as u
def er(q): return ER+u.quote(q)
def ent(hy,en,tax,form,yr,src): return {"name_hy":hy,"name_en":en,"tax_id":tax,"form":form,"registered_year":yr,"source_url":src}
rows=[
{"developer":"New Age","role":"developer",
 "legal_entities":[ent("«ՆՅՈՒ ԷՅՋ ՔՈՆՍԹՐԱՔՇՆ» ՍՊԸ","New Age Construction LLC","05548225","ՍՊԸ",2019,er("նյու էյջ"))],
 "founded_year":2019,"datalex_names":["ՆՅՈՒ ԷՅՋ ՔՈՆՍԹՐԱՔՇՆ","ՆՅՈՒ ԷՅՋ ՔՈՆՍԹՐԱՔԹ","ՆՅՈՒ ԷՅՋ ՀԱՈՒՍԻՆԳ"],"datalex_tax_id":"05548225",
 "news_issues":[],
 "positives":[
  {"title":"CBA decision 1/238 Ա (16.07.2025) registering «ՆՅՈՒ ԷՅՋ ՔՈՆՍԹՐԱՔՇՆ» ՍՊԸ coupon bond prospectus","url":"https://www.cba.am/hy/Publications/8713/","summary":"Central Bank registered the company's named coupon bond issue (placement via Sirius Capital CJSC, Aug-Oct 2025, per https://banks.am/am/news/capital_market/29612); company is a listed issuer on AMX."},
  {"title":"New Age Construction on myhome.am (Ameriabank platform) developer partners","url":"https://myhome.am/partners/developers/5","summary":"Listed developer partner; social profiles claim 47,000+ m2 built and 340+ apartments; completed G. Nzhdeh 11/11 in Gyumri."}],
 "confidence":"high",
 "notes":"myhome.am building pages name the builder «Նյու Էյջ Քոնսթրաքշն ՍՊԸ» (office Argishti 7/13, 7/10 Yerevan); other listings say \"НЬЮ ЭЙДЖ КОНСТРАКШН\" ООО. e-register: «ՆՅՈՒ ԷՅՋ ՔՈՆՍԹՐԱՔՇՆ» ՍՊԸ reg 03-04-2019, registered address Tbilisyan hwy 1, Gyumri (consistent with completed Gyumri project). Two sister entities at the same Gyumri address registered Oct 2024: «ՆՅՈՒ ԷՅՋ ՔՈՆՍԹՐԱՔԹ» ՍՊԸ (05564169) and «ՆՅՈՒ ԷՅՋ ՀԱՈՒՍԻՆԳ» ՍՊԸ (05564134) - likely project SPVs; search them too. Unrelated namesakes: «ՆՅՈՒ ԷՅՋ» ՍՊԸ 00146604, «ՆՅՈՒ ԷՅՋ» ՀՄՏ (condominium at Argishti 7/10). Bond issuance means financial statements are public via CBA/AMX."},
{"developer":"National Group","role":"developer",
 "legal_entities":[ent("«ՆԱՑԻՈՆԱԼ ԳՐՈՒՊ» ՍՊԸ","National Group LLC","02275533","ՍՊԸ",2018,er("նացիոնալ գրուպ"))],
 "founded_year":2018,"datalex_names":["ՆԱՑԻՈՆԱԼ ԳՐՈՒՊ","ՆԵՅՇՆԼ ԳՐՈՒՊ"],"datalex_tax_id":"02275533",
 "news_issues":[],
 "positives":[
  {"title":"Nor Avan Complex - six 16/18-storey buildings at Acharyan 37/1","url":"https://nationalgroup.am/index.php/en/nor-avan-complex/","summary":"Large 6-building complex in Avan; earlier completed building at Garegin Nzhdeh 23/3. Company claims 30+ years of team experience in construction and building materials."}],
 "confidence":"high",
 "notes":"nationalgroup.am shows 'ՆԱՑԻՈՆԱԼ ԳՐՈՒՊ ՍՊԸ'. e-register: «ՆԱՑԻՈՆԱԼ ԳՐՈՒՊ» ՍՊԸ reg 29-08-2018, address G. Nzhdeh 23/6 - matches construction.am company page (since 2018, 23/6 Garegin Nzhdeh St.). No negative news found (web search budget exhausted mid-task; only site/registry checks and limited news-site search done)."},
{"developer":"Aygedzor Construction Company","role":"developer",
 "legal_entities":[ent("«ԱՅԳԵՁՈՐ» ՍՊԸ","Aygedzor LLC","00815501","ՍՊԸ",1996,"https://www.construction.am/companies/aygedzor/")],
 "founded_year":1996,"datalex_names":["ԱՅԳԵՁՈՐ"],"datalex_tax_id":"00815501",
 "news_issues":[],
 "positives":[
  {"title":"Aygedzor Construction Company - since 1996","url":"https://www.construction.am/companies/aygedzor/","summary":"Long-established general contractor/developer (director Aramayis Vorskanyan); completed 'Aygedzor' residential complex (Davit Anhaght 11/12) and 'Solar' complex (Alma-Ata 1/4) per aygedzor.am."}],
 "confidence":"high",
 "notes":"construction.am: \"Aygedzor\" LLC, TIN 00815501, 35/3 Acharyan St.; aygedzor.am footer shows the same address and '«Այգեձոր» ՍՊԸ'. e-register confirms reg 26-04-1996, address Acharyan 35/3. CAUTION for court search: 'ԱՅԳԵՁՈՐ' is also a Yerevan street/district and a village, and there are namesakes (dissolved «ԱՅԳԵՁՈՐ» Ա/Կ 02202038, «ԱՅԳԵՁՈՐ» ՀՄՏ 00257165) - filter by tax ID 00815501."},
{"developer":"Building Capital","role":"developer",
 "legal_entities":[ent("«ԲԻԼԴԻՆԳ ԿԱՊԻՏԱԼ» ՍՊԸ","Building Capital LLC","00144692","ՍՊԸ",2015,er("բիլդինգ կապիտալ")),
  ent("«ԿԱՊԻՏԱԼ ԿՈՄՊԼԵՔՍ ԳՐՈՒՊ» ՍՊԸ","Capital Complex Group LLC","00141462","ՍՊԸ",2015,er("կապիտալ կոմպլեքս"))],
 "founded_year":2015,"datalex_names":["ԲԻԼԴԻՆԳ ԿԱՊԻՏԱԼ","ԿԱՊԻՏԱԼ ԿՈՄՊԼԵՔՍ ԳՐՈՒՊ"],"datalex_tax_id":"00144692",
 "news_issues":[],
 "positives":[],
 "confidence":"high",
 "notes":"Hint verified: e-register has exactly one «ԲԻԼԴԻՆԳ ԿԱՊԻՏԱԼ» ՍՊԸ, tax ID 00144692, reg 09-07-2015 (construction.am: 'Since 2015'), registered address G-1 district 41/25 Yerevan - matches the project 'Building Capital · G-1 District'. The contact email capitalcomplexgroup@gmail.com and construction.am office address (4 Hrachya Kochar St.) match «ԿԱՊԻՏԱԼ ԿՈՄՊԼԵՔՍ ԳՐՈՒՊ» ՍՊԸ (00141462, reg 20-03-2015, Kochar 4) - a sister company; search both. No news found (limited news search)."},
{"developer":"Kechi Hangstyan Tun  (Park Royal Tsaghkadzor)","role":"developer",
 "legal_entities":[ent("«ԿԵՉԻ ՀԱՆԳՍՏՅԱՆ ՏՈՒՆ» ՍՊԸ","Kechi Rest House LLC","03016367","ՍՊԸ",2005,er("հանգստյան տուն"))],
 "founded_year":2005,"datalex_names":["ԿԵՉԻ ՀԱՆԳՍՏՅԱՆ ՏՈՒՆ","ՔԵՉԻ ՀԱՆԳՍՏՅԱՆ ՏՈՒՆ","ԿԵՉԻ"],"datalex_tax_id":"03016367",
 "news_issues":[],
 "positives":[{"title":"ACBA Bank mortgage partner developers list","url":"https://www.acba.am/hy/individuals/loans/mortgage/constructors#10181","summary":"Park Royal Tsaghkadzor listed among ACBA Bank mortgage partner projects (also listed by Unibank partner developers)."}],
 "confidence":"high",
 "notes":"Display name is a transliteration of «Կեչի հանգստյան տուն». e-register: «ԿԵՉԻ ՀԱՆԳՍՏՅԱՆ ՏՈՒՆ» ՍՊԸ reg 08-11-2005, address Kh. Kecharetsu St., Tsaghkadzor - matches project address Khachatur Kecharetsi 4, Tsaghkadzor (site of the former Kechi rest house). Registered spelling uses Կ (ԿԵՉԻ), not Ք. Unrelated/unconfirmed: «ՊԱՐԿ ՌՈՅԱԼ» ՓԲԸ (00521851, Yerevan, reg 2023) - not linked by evidence."},
{"developer":"Noy Residence","role":"developer",
 "legal_entities":[ent("«ՆՈՅ ՌԵԶԻԴԵՆՍ» ՍՊԸ","Noy Residence LLC","01335296","ՍՊԸ",2023,er("նոյ ռեզիդենս"))],
 "founded_year":2023,"datalex_names":["ՆՈՅ ՌԵԶԻԴԵՆՍ"],"datalex_tax_id":"01335296",
 "news_issues":[],"positives":[],
 "confidence":"high",
 "notes":"Only e-register match: «ՆՈՅ ՌԵԶԻԴԵՆՍ» ՍՊԸ reg 14-03-2023 (email noyresidence2023@gmail.com matches year), address Leningradyan 23/1 - Leningradyan St. is the former name of Kirk Kerkorian St., and myhome.am builder address is 'Լենինգրադյան 23/23' = project address. Neighbouring project Kristal Bilding (Kirk Kerkorian 23/15, «ԱՄ ՔԸՆՍԹՐԱՔԹ» ՍՊԸ) is nearby; no link established."},
{"developer":"New Masis","role":"developer",
 "legal_entities":[],
 "founded_year":None,"datalex_names":["ՆՅՈՒ ՄԱՍԻՍ","ՆՈՐ ՄԱՍԻՍ"],"datalex_tax_id":None,
 "news_issues":[],"positives":[],
 "confidence":"low",
 "notes":"myhome.am brand 'Նոր Մասիս / New Masis', builder address Masis, M. Heratsi 20 (project site), phone +374 41 320-320. No e-register company named ՆՅՈՒ ՄԱՍԻՍ / ՆՈՐ ՄԱՍԻՍ found - brand likely built by a differently named LLC. Phone pattern (41 320-320) is near-identical to BEST MASIS (41 320-220), suggesting the same group; BEST MASIS links to arcsisrealty.com («ԱՐՔՍԻՍ» ՍՊԸ, Masis, 04463559)."},
{"developer":"Avan Project","role":"developer",
 "legal_entities":[ent("«ԱՎԱՆ ՊՐՈՋԵՔԹ» ՍՊԸ","Avan Project LLC","02818559","ՍՊԸ",2019,er("ավան պրոջեքթ")),
  ent("«ՆՅՈՒ ՍԻԹԻ ՊՐՈՋԵԿՏՍ» ՍՊԸ","New City Projects LLC","02698921","ՍՊԸ",2019,"https://newcity.am/hy")],
 "founded_year":2019,"datalex_names":["ԱՎԱՆ ՊՐՈՋԵՔԹ","ՆՅՈՒ ՍԻԹԻ ՊՐՈՋԵԿՏՍ"],"datalex_tax_id":"02818559",
 "news_issues":[],"positives":[],
 "confidence":"medium",
 "notes":"myhome.am builder brand 'ԱՎԱՆ ՊՐՈՋԵՔԹ ՍՊԸ / Avan Project LLC' (Acharyan 39/23). e-register exact match «ԱՎԱՆ ՊՐՈՋԵՔԹ» ՍՊԸ reg 09-12-2019 (Chkalov 16). Website newcity.am belongs to brand 'New City Projects'; e-register «ՆՅՈՒ ՍԻԹԻ ՊՐՈՋԵԿՏՍ» ՍՊԸ (02698921, Buzand 7) is the probable parent/brand company - link inferred from the website only."},
{"developer":"BEST MASIS","role":"developer",
 "legal_entities":[],
 "founded_year":None,"datalex_names":["ԲԵՍԹ ՄԱՍԻՍ","ԲԵՍՏ ՄԱՍԻՍ"],"datalex_tax_id":None,
 "news_issues":[],"positives":[],
 "confidence":"low",
 "notes":"myhome.am brand 'ԲԵՍԹ ՄԱՍԻՍ', builder address Masis, Azatamartikneri 41. No registered company with that name found in e-register. Website arcsisrealty.com: «ԱՐՔՍԻՍ» ՍՊԸ (04463559, reg 16-01-2026, Masis 11th St. 10) - probably a realty/sales company, not confirmed as developer. Likely same group as 'New Masis' (phones 41 320-220 / 41 320-320)."},
{"developer":"GNELYAN BUILDING","role":"developer",
 "legal_entities":[ent("«ԳՆԵԼՅԱՆ» ՍՊԸ","Gnelyan LLC","04248446","ՍՊԸ",2024,er("գնելյան"))],
 "founded_year":None,"datalex_names":["ԳՆԵԼՅԱՆ","ԳՆԵԼՅԱՆ ԲԻԼԴԻՆԳ"],"datalex_tax_id":"04248446",
 "news_issues":[],"positives":[],
 "confidence":"medium",
 "notes":"myhome.am brand 'ԳՆԵԼՅԱՆ ԲԻԼԴԻՆԳ', email gnelyanllc@gmail.com, project 7th District 7th St. 4 Masis, builder address Masis Yerevanyan 20. The only company in e-register is «ԳՆԵԼՅԱՆ» ՍՊԸ registered in Masis (1st district), reg 09-01-2024 - matches town and 'gnelyanllc' email; reg date is recent for a 'finished' project (possible re-registration or project SPV)."},
{"developer":"MASIS CENTRAL RESIDENTIAL COMPLEX","role":"developer",
 "legal_entities":[ent("«ՄԵՏՐՈՒՄ ԻՆՎԵՍՏ» ՍՊԸ (candidate)","Metrum Invest LLC","02850523","ՍՊԸ",2021,er("մետրում ինվեստ"))],
 "founded_year":None,"datalex_names":["ՄԵՏՐՈՒՄ ԻՆՎԵՍՏ","ՄԵՏՐՈՒՄ","ՄԱՍԻՍ ՑԵՆՏՐԱԼ"],"datalex_tax_id":None,
 "news_issues":[],"positives":[],
 "confidence":"low",
 "notes":"myhome.am brand 'ՄԱՍԻՍ ՑԵՆՏՐԱԼ ՌԵԶԻԴԵՆՏԱԼ ԿՈՄՊԼԵՔՍ', Araratyan 5 Masis; website metruminvest.am and email metrumllc@gmail.com point to the Metrum Invest group. e-register has a family of Metrum entities at Verin Antarayin 136/2-136/3: «ՄԵՏՐՈՒՄ ԻՆՎԵՍՏ» ՍՊԸ 02850523 (2021), «ՄԵՏՐՈՒՄ ԻՆՎԵՍՏ ԳՐՈՒՊ» ՍՊԸ 02886243 (2023), plus project SPVs «...ՊԱՐԿ», «...ՌՈՒԲԻՆՅԱՆՑ», «...ՄԱՐԱՇ», «...ԳԱՐԴԵՆ». No plain «ՄԵՏՐՈՒՄ» ՍՊԸ and no Masis-specific entity found; which entity holds the Masis permit is unverified."},
{"developer":"Nairi Residence","role":"developer",
 "legal_entities":[],
 "founded_year":None,"datalex_names":["ՆԱԻՐԻ ՌԵԶԻԴԵՆՍ","Վ-ՌՌ ՔՈՆՍԹՐԱՔՇՆ"],"datalex_tax_id":None,
 "news_issues":[],"positives":[],
 "confidence":"low",
 "notes":"myhome.am brand 'Նաիրի Ռեզիդենս', project/builder address Yeghvard, Yerevanyan hwy 8/7 (Kotayk); email v-rr.construction@mail.ru suggests an LLC named like 'V-RR Construction'. No e-register match for ՆԱԻՐԻ ՌԵԶԻԴԵՆՍ or Վ-ՌՌ variants. 'ՆԱԻՐԻ' alone returns 200+ companies - do not search the court DB by 'ՆԱԻՐԻ' alone."},
{"developer":"NAIRI HOUSE","role":"developer",
 "legal_entities":[ent("«ՆԱԻՐԻ ՀԱՈՒԶ» ՍՊԸ (candidate)","Nairi House LLC","02832249","ՍՊԸ",2020,er("նաիրի"))],
 "founded_year":None,"datalex_names":["ՆԱԻՐԻ ՀԱՈՒԶ","ՆԱԻՐԻ ՀԱՈՒՍ"],"datalex_tax_id":None,
 "news_issues":[],"positives":[],
 "confidence":"low",
 "notes":"myhome.am brand 'Նաիրի Հաուս', project at Ara Martirosyan 10 (myhome: Kasakh, Kotayk; novostroiki: Davtashen), builder address Yerevan, Halabyan 31 apt 46. e-register has «ՆԱԻՐԻ ՀԱՈՒԶ» ՍՊԸ (02832249, reg 28-09-2020, Paronyan 21/11) - name matches but address does not; unverified."},
{"developer":"SARILANJ BUILDING","role":"developer",
 "legal_entities":[ent("«ՍԱՐԻԼԱՆՋ ԲՈՒԻԼԴԻՆԳ» ՍՊԸ","Sarilanj Building LLC","02862263","ՍՊԸ",2022,er("սարիլանջ"))],
 "founded_year":2022,"datalex_names":["ՍԱՐԻԼԱՆՋ ԲՈՒԻԼԴԻՆԳ","ՍԱՐԻԼԱՆՋ ԲԻԼԴԻՆԳ"],"datalex_tax_id":"02862263",
 "news_issues":[],"positives":[],
 "confidence":"high",
 "notes":"myhome.am builder 'ՍԱՐԻԼԱՆՋ ԲՈՒԻԼԴԻՆԳ ՍՊԸ'; single e-register match «ՍԱՐԻԼԱՆՋ ԲՈՒԻԼԴԻՆԳ» ՍՊԸ reg 29-04-2022 (Arami 64). Note spelling ԲՈՒԻԼԴԻՆԳ (not ԲԻԼԴԻՆԳ). The builder phone +374 98 908 908 is RED Group / RED Invest Group's number (redgroup.am), so sales are likely via RED Invest (same agent as EDNO Group)."},
{"developer":"Residence 50","role":"developer",
 "legal_entities":[],
 "founded_year":None,"datalex_names":["ՌԵԶԻԴԵՆՍ 50","ՌԵԶԻԴԵՆՍ ՀԻՍՈՒՆ"],"datalex_tax_id":None,
 "news_issues":[],"positives":[],
 "confidence":"low",
 "notes":"Brand only (residence50.am, myhome.am builder address Garegin Hovsepyan 50, Nork-Marash; phone +374 44 030-004). No e-register company with 'ՌԵԶԻԴԵՆՍ 50' found; legal developer unknown."},
{"developer":"Am Kynstrakt","role":"developer",
 "legal_entities":[ent("«ԱՄ ՔԸՆՍԹՐԱՔԹ» ՍՊԸ","AM Construct LLC","01334852","ՍՊԸ",2023,"https://ar-go.am/project/crystal-building-bnakeli-hamalir")],
 "founded_year":2023,"datalex_names":["ԱՄ ՔԸՆՍԹՐԱՔԹ","ԱՄ ՔՈՆՍԹՐԱՔԹ"],"datalex_tax_id":"01334852",
 "news_issues":[],
 "positives":[{"title":"Crystal Building residential complex - bank partner Fast Bank","url":"https://ar-go.am/project/crystal-building-bnakeli-hamalir","summary":"518 apartments at Kirk Kerkorian 23/15; builder «ՍԱՖԱՐՅԱՆ ՇԻՆ» ՍՊԸ; bank «ՖԱՍԹ ԲԱՆԿ» ՓԲԸ; construction 07.2024-01.2028."}],
 "confidence":"high",
 "notes":"ar-go.am names developer «ԱՄ ՔԸՆՍԹՐԱՔԹ» ՍՊԸ; e-register single match reg 06-03-2023, Silikyan district 4th St. 9. Contractor «ՍԱՖԱՐՅԱՆ ՇԻՆ» ՍՊԸ. Phone +374 55 200707 is ARGO Realty (sales agent) shared across its listings."},
{"developer":"S․t․sh․ Piramida","role":"developer",
 "legal_entities":[ent("«Ս.Տ.Շ.-ՊԻՐԱՄԻԴԱ» ՍՊԸ","S.T.Sh.-Piramida LLC","04414867","ՍՊԸ",2002,er("պիրամիդա"))],
 "founded_year":2002,"datalex_names":["Ս.Տ.Շ.-ՊԻՐԱՄԻԴԱ","Ս.Տ.Շ. ՊԻՐԱՄԻԴԱ","ՍՏՇ ՊԻՐԱՄԻԴԱ"],"datalex_tax_id":"04414867",
 "news_issues":[],
 "positives":[{"title":"Elize residential complex - bank partner Unibank","url":"https://ar-go.am/project/elize","summary":"96 apartments at Davtashen 4th district 46/9; builder «ՄԻԿՇԻՆ» ՍՊԸ; bank «ՅՈՒՆԻԲԱՆԿ» ՓԲԸ; construction 02.2023-12.2026; building permit posted."}],
 "confidence":"high",
 "notes":"ar-go.am names developer «Ս․Տ․Շ․ ՊԻՐԱՄԻԴԱ» ՍՊԸ; e-register has «Ս.Տ.Շ.-ՊԻՐԱՄԻԴԱ» ՍՊԸ reg 10-05-2002, Sayat-Nova 20/2 Yerevan (only S.T.Sh. variant). Court DB may store with hyphen/dots variations - try all. Do not search 'ՊԻՐԱՄԻԴԱ' alone (8+ namesakes). Contractor «ՄԻԿՇԻՆ» ՍՊԸ."},
{"developer":"Royal Bilding","role":"developer",
 "legal_entities":[ent("«ՌՈՅԱԼ ԲԻԼԴԻՆԳ» ՍՊԸ","Royal Building LLC","02853247","ՍՊԸ",2022,"https://ar-go.am/project/kaskad-park-bnakeli-hamalir")],
 "founded_year":2022,"datalex_names":["ՌՈՅԱԼ ԲԻԼԴԻՆԳ"],"datalex_tax_id":"02853247",
 "news_issues":[],
 "positives":[{"title":"Kaskad Park residential complex - bank partner Ameriabank","url":"https://ar-go.am/project/kaskad-park-bnakeli-hamalir","summary":"Antarayin 154-156, Kentron; builder «ԷՅ - ՋԻ ՔՈՆՍԹՐԱՔՇՆ» ՍՊԸ; bank «ԱՄԵՐԻԱԲԱՆԿ» ՓԲԸ; completion planned Dec 2026."}],
 "confidence":"high",
 "notes":"ar-go.am names developer «ՌՈՅԱԼ ԲԻԼԴԻՆԳ» ՍՊԸ; e-register single match reg 17-02-2022, Mashtots 24 apt 7. Contractor «ԷՅ-ՋԻ ՔՈՆՍԹՐԱՔՇՆ» ՍՊԸ."}
]
prev=json.load(open('r3_part1.json'))
allr=prev+rows
order=[d['developer'] for d in json.load(open('chunk_3.json'))]
m={r['developer']:r for r in allr}
assert set(order)==set(m), set(order)^set(m)
json.dump([m[k] for k in order],open('research_3.json','w'),ensure_ascii=False,indent=1)
print(len(order))
