import json
RG="https://redgroup.am/projects/"
IDB="https://idbank.am/documents/IDBank%20constructors%20pptt.pdf"
def ent(hy,en,form,url,tax=None,yr=None): return {"name_hy":hy,"name_en":en,"tax_id":tax,"form":form,"registered_year":yr,"source_url":url}
def rec(dev,role,ents,dl,issues,pos,conf,notes,fy=None):
    return {"developer":dev,"role":role,"legal_entities":ents,"founded_year":fy,"datalex_names":dl,
            "tax_ids":[e["tax_id"] for e in ents if e["tax_id"]],"news_issues":issues,"positives":pos,
            "entity_confidence":conf,"notes":notes}
SALES=" Sales agent RED Invest Group (redinvest.am / redgroup.am, Buzand 107) is a brokerage, not the developer."
out=[
rec("Advanced development (sales: RED Invest Group)","developer",
 [ent("Ըդվանսդ Դիվելըփմենթ","Advanced Development","ՍՊԸ",RG+"bnakarankarucapatoxic-nornorqum-garunavan3")],
 ["Ըդվանսդ Դիվելըփմենթ","Ըդվասդ Դիվելըփմենթ","Էդվանսդ Դեվելոփմենթ"],[],
 [{"title":"Partner developer of IDBank (Garunavan 4, Bagrevand)","url":IDB,"summary":"IDBank's mortgage-partner developer list names ԸԴՎԱՆՍԴ ԴԻՎԵԼԸՓՄԵՆԹ ՍՊԸ as developer of Garunavan 4 in Nor Nork."},
  {"title":"Garunavan housing series designed with Tuscan architects","url":"https://tuscan.am/en/projects/architecture/garunavan-housing-project-yerevan/general","summary":"Garunavan I-IV villa/low-rise district in Nor Nork built by Advanced Development with architecture by Tuscan LLC; Garunavan 2 (2019) and 3 (2022) completed."}],
 "high","redgroup.am Armenian project pages (Garunavan 2 and 3) state Կառուցապատող «Ըդվանսդ Դիվելըփմենթ» ՍՊԸ (Garunavan 2 page misspells it «Ըդվասդ»); architect «Թոսքան» ՍՊԸ. Same name in capitals in IDBank partner list. Director reported as Armen Khodabakhshyan (garunavan.am, via search snippet). Spyur listing /companies/advanced-development/34278 exists in search index but page now returns error. Tax ID not found."+SALES),
rec("Royal Hills (sales: RED Invest Group)","developer",
 [ent("Ռոյալ Հիլզ","Royal Hills","ՍՊԸ",RG+"bnakarankarucapatoxic-cascade-club")],
 ["Ռոյալ Հիլզ","Ռոյալ Հիլս"],[],
 [{"title":"Cascade Park backed by Inecobank as partner bank","url":RG+"bnakarankarucapatoxic-cascade-club","summary":"Project page lists Inecobank as partner bank, Architon LLC as designer and Global Building Development LLC as builder."}],
 "high","redgroup.am Cascade Park page: Կառուցապատող՝ «Ռոյալ Հիլզ» ՍՊԸ, also managing company; designer «Արխիտոն» ՍՊԸ, builder «Գլոբալ Բիլդինգ Դեվելոփմենթ» ՍՊԸ; construction start planned June 2026, finish Dec 2029. Note: an ar-go.am snippet describes 'Cascade Park' (2 buildings, 43 flats, completion H2 2025) as built by 'Royal Building' LLC - possibly an earlier/different transliteration; the record's other sources (gtbholdings.com, dignisi.am) hint at a possible link to GTB Holdings' 'GTB Cascade' - unverified. Not to be confused with Cascade Hills complex (cascadehills.am). Tax ID not found."+SALES),
rec("Argavand Towers  (sales: RED Invest Group)","developer",
 [ent("Արգավանդ Թաուերս","Argavand Towers","ՓԲԸ",RG+"bnakarankarucapatoxic-argavand-towers")],
 ["Արգավանդ Թաուերս","Արգավանդ Տաուերս"],[],
 [{"title":"Argavand Towers partner banks Armeconombank and IDBank","url":RG+"bnakarankarucapatoxic-argavand-towers","summary":"Project page lists Armeconombank and IDBank as partner banks, designer 34 Project LLC and builder Armat Construction CJSC; ~520 units, construction planned Sept 2026-Dec 2030."}],
 "high","redgroup.am Armenian page states Կառուցապատող՝ «Արգավանդ Թաուերս» ՓԲԸ (CJSC), while local projects.json English text says 'Argavand Towers LLC' - Armenian page is authoritative for form. Designer «34 Փրոջեքթ» ՍՊԸ, builder «Արմատ Քոնսթրաքշն» ՓԲԸ. Project not yet started. Unrelated: Argavand Furniture (argavand.am). Tax ID not found."+SALES),
rec("Omega Plus (sales: RED Invest Group)","developer",
 [ent("Օմեգա Պլյուս","Omega Plus","ՍՊԸ",RG+"bnakarankarucapatoxic-theview")],
 ["Օմեգա Պլյուս","Օմեգա Պլյուս Շին"],[],
 [{"title":"IDBank mortgage partner - The View, Lvovyan 108/2","url":IDB,"summary":"IDBank lists ՕՄԵԳԱ ՊԼՅՈՒՍ ՍՊԸ (Nor Nork) with The View project, building permit valid to 15.12.2024."}],
 "high","redgroup.am The View page: Կառուցապատող՝ «Օմեգա Պլյուս» ՍՊԸ, builder «Միդիս Քնսթրաքշն» ՍՊԸ, construction start 01.12.2021. IDBank partner list spells ՕՄԵԳԱ ՊԼՅՈՒՍ. Generic name - other same-name companies may exist in registry. Tax ID not found."+SALES),
rec("Gevorg Darbinyan (sales: RED Invest Group)","developer",
 [ent("Գևորգ Դարբինյան","Gevorg Darbinyan","unknown (individual or ԱՁ)",RG+"bnakaran-karucapatoxic-fordream")],
 ["Գևորգ Դարբինյան"],[],
 [{"title":"For Dream Residence with First Bank partnership","url":RG+"bnakaran-karucapatoxic-fordream","summary":"159-apartment building at Acharyan 57/12, Avan, marketed with Fast Bank as partner bank."}],
 "low","redgroup.am page lists Կառուցապատող՝ «Գևորգ Դարբինյան» with no legal form - developer appears to be a private person (possibly a sole proprietor ԱՁ or the permit holder), so the actual LLC, if any, is unidentified. For datalex search by person name; common name - many namesakes. Partner bank «Ֆասթ Բանկ» ՓԲԸ."+SALES),
rec("Villa Town House  (sales: RED Invest Group)","developer",
 [ent("Գլորիա Ինվեստ","Gloria Invest","ՍՊԸ",RG+"bnakaran-karucapatoxic-davtashentown2"),
  ent("Վիլլա Թաուն Հաուս","Villa Town House","ՍՊԸ",RG+"bnakaran-karucapatoxic-davtashentown")],
 ["Գլորիա Ինվեստ","Վիլլա Թաուն Հաուս","Վիլլա Տաուն Հաուս"],[],
 [{"title":"Davtashen Town family districts with Fast Bank partnership","url":RG+"bnakaran-karucapatoxic-davtashentown2","summary":"Davtashen Town 1 (completed Feb 2025) and Davtashen Town 2 (Sose St 22) townhouse districts, partner bank Fast Bank, designer Profenergy Group, builder Lox Building."}],
 "medium","For Davtashen Town 2 the Armenian redgroup.am page names Կառուցապատող «ԳԼՈՐԻԱ ԻՆՎԵՍՏ» ՍՊԸ (start 01.11.2024, end 01.12.2025), whereas the English redinvest.am text / projects.json says 'Villa Town House LLC' (likely copied from Davtashen Town 1). Villa Town House ՍՊԸ is confirmed developer of Davtashen Town 1 (Samvel Gevorgyan 106/21). Same designer «Պրոֆէներջի Գրուպ» ՍՊԸ and builder «Լոքս Բիլդինգ» ՍՊԸ on both, suggesting related companies. Tax IDs not found."+SALES),
rec("Villa Town House","developer",
 [ent("Վիլլա Թաուն Հաուս","Villa Town House","ՍՊԸ",RG+"bnakaran-karucapatoxic-davtashentown")],
 ["Վիլլա Թաուն Հաուս","Վիլլա Տաուն Հաուս"],[],
 [{"title":"Davtashen Town completed family district","url":RG+"bnakaran-karucapatoxic-davtashentown","summary":"Davtashen Town (4-5 room units, 144-176 m2) built 03.2023-02.2025 with Fast Bank as partner bank."}],
 "high","redgroup.am Davtashen Town page: Կառուցապատող «Վիլլա Թաուն Հաուս» ՍՊԸ, designer «Պրոֆէներջի Գրուպ» ՍՊԸ, builder «Լոքս Բիլդինգ» ՍՊԸ. Same company as the 'Villa Town House (sales: RED Invest Group)' record; the follow-up Davtashen Town 2 lists «Գլորիա Ինվեստ» ՍՊԸ. Tax ID not found."+SALES),
rec("S. S. Brothers  (sales: RED Invest Group)","developer",
 [ent("Ս.Ս. Եղբայրներ","S. S. Brothers","ՍՊԸ",RG+"bnakarankarucapatoxic-21street")],
 ["Ս.Ս. Եղբայրներ","Ս.Ս.Եղբայրներ","Էս Էս Բրադերս"],[],
 [{"title":"21 Street building with Ardshinbank partnership","url":RG+"bnakarankarucapatoxic-21street","summary":"8-storey residential building at Arabkir 21 with Ardshinbank as partner bank; completion slipped from Dec 2025 to planned March 2026."}],
 "medium","redgroup.am page: Կառուցապատող՝ «Ս․Ս․ Եղբայրներ» ՍՊԸ (Armenian translation of 'Brothers', not a transliteration); registry spelling of initials/punctuation uncertain. Note completion date shifted (projects.json 2025-12 vs page 'planned March 2026'). Tax ID not found."+SALES),
rec("Ecology Construction  (sales: RED Invest Group)","developer",
 [ent("Էկոլոջի Քոնսթրաքշն","Ecology Construction","ՍՊԸ",RG+"bnakarankarucapatoxic-erebuni")],
 ["Էկոլոջի Քոնսթրաքշն","Էկոլոջի Քոնստրաքշն","Էկոլոջի Կոնստրուկցիա"],[],
 [{"title":"Converse Bank mortgage program for Ecology Construction project","url":"https://www.conversebank.am/hy/ecologyconstruction/","summary":"Converse Bank runs a dedicated mortgage/renovation loan page for Ecology Construction LLC buyers with a builder escrow-type account."}],
 "high","redgroup.am Erebuni page: Կառուցապատող՝ «Էկոլոջի քոնսթրաքշն» ՍՊԸ, builder «Դ և Ս Քոնսթրաքշն», technical supervisor ԱՁ Vrezh Hrant...; project David Bek 1/25, 11.2020-11.2021. Converse Bank spells «Էկոլոջի Քոնստրաքշն». Tax ID not found."+SALES),
]
json.dump(out,open("/Users/ksh/agents/news-agent/armenia-new-builds/scraper/.work/reputation_3/D/part1.json","w"),ensure_ascii=False,indent=1)
