import json
EV_HY="https://www.evoca.am/hy/construction-companies"
AG="https://ar-go.am/partners"
def E(name_hy,name_en,form="ՍՊԸ",src="",tax=None,yr=None): return {"name_hy":name_hy,"name_en":name_en,"tax_id":tax,"form":form,"registered_year":yr,"source_url":src}
def R(dev,role,ents,names,conf,notes,issues=(),pos=(),founded=None):
    return {"developer":dev,"role":role,"legal_entities":ents,"founded_year":founded,"datalex_names":names,"news_issues":list(issues),"positives":list(pos),"confidence":conf,"notes":notes}
out=[]
bedeck_issues=[
 {"date":"2025-05-23","title":"Worker (37) fell from 12th floor of Bedeck LLC building under construction at Pirumyanner 13, Davtashen; criminal proceeding opened","url":"https://168.am/2025/05/23/2220041.html","summary":"Death attributed to non-compliance with work safety rules at the Bedeck Davtashen complex site (same address as the Pars project); investigative department opened a criminal case."},
 {"date":"2024-10-04","title":"Hetq/168.am: company of ex-MP Mher Sedrakyan's son wins 743m AMD Genocide Memorial renovation contract","url":"https://168.am/2024/10/04/2106166.html","summary":"Bedeck LLC 75% owned by David Sedrakyan (ex-MP, 'Hayastan' faction; son of ex-RPA MP Mher Sedrakyan), 25% Garnik Avetisyan (100% owner 2009-2019). Politically-connected large state/municipal contracts (5.39bn AMD with Yerevan municipality/police in 2021-22). Reputational/PEP concern, not a legal finding."},
 {"date":"2026-03-19","title":"Factor.am: 573m AMD to Bedeck for works for 8th European Political Community summit","url":"https://factor.am/996690.html","summary":"Further state procurement to the Sedrakyan-owned company; framed critically as politically connected."}]
bedeck_pos=[{"title":"Large public-works contractor (Genocide Memorial renovation, bridges, colleges); publishes annual reports 2019-2025","url":"https://bedeck.am/about-us","summary":"Bedeck LLC founded 2009, director Garnik Avetisyan; >1,000 workers engaged; several residential projects (Davtashen, Masis, Nor Nork, Shengavit)."}]
for dev,note in [("Bedeck Masis","Same company as display name 'Pars' (both on bedeck.am). myhome.am developer label 'Բիդեք Մասիս'; the parent/brand is «Բիդեք» ՍՊԸ (founded 2009, director Garnik Avetisyan). Project-specific SPV name for Masis (Heratsi 28/1) not confirmed — 'ԲԻԴԵՔ ՄԱՍԻՍ' queued as a guess."),
                 ("Pars","Same company group as 'Bedeck Masis'. myhome.am lists developer «Պարս» ՍՊԸ for Pirumyanner 13G (Bedeck Davtashen complex); site bedeck.am. «Պարս» is likely the land-owning/developer SPV, Bedeck LLC the builder. 'ՊԱՐՍ' is a short name that may match unrelated companies in datalex.")]:
    ents=[E("«Բիդեք» ՍՊԸ","Bedeck LLC",src="https://bedeck.am/about-us",yr=2009)]
    if dev=="Pars": ents.insert(0,E("«Պարս» ՍՊԸ","Pars LLC",src="https://myhome.am/en/building/95"))
    out.append(R(dev,"developer",ents,(["ՊԱՐՍ"] if dev=="Pars" else [])+["ԲԻԴԵՔ","ԲԻԴԵՔ ՄԱՍԻՍ","ԲԻԴԵՔ ՔՈՆՍԹՐԱՔՇՆ"],"high" if dev=="Pars" else "medium",note,bedeck_issues,bedeck_pos,2009))
out.append(R("DGA Construction","developer",[E("«ԴԻ ՋԻ ԷՅ ՔԸՆՍԹՐԱՔՇՆ» ՍՊԸ","DGA CONSTRUCTION LLC",src=EV_HY)],["ԴԻ ՋԻ ԷՅ ՔԸՆՍԹՐԱՔՇՆ","ԴԻ ՋԻ ԷՅ ՔՈՆՍԹՐԱՔՇՆ","ԴԻՋԻԷՅ ՔԸՆՍԹՐԱՔՇՆ"],"high",
  "Evoca developer list gives «ԴԻ ՋԻ ԷՅ ՔԸՆՍԹՐԱՔՇՆ» ՍՊԸ, Hatis St 1/85 Abovyan, same phone as dgaconstruction.am. Company also runs concrete production and machinery rental. No news found.",
  pos=[{"title":"Evoca Bank mortgage partner developer","url":"https://www.evoca.am/en/construction-companies","summary":"Listed as partner developer for the Abovyan project."}]))
out.append(R("Brawerk","developer",[E("«Braverk» ՍՊԸ (formerly «Metsn Erik» ՍՊԸ)","Brawerk LLC (formerly Metsn Erik LLC)",src="https://brawerk.am/hy/terms-and-conditions")],["ԲՐԱՎԵՐԿ","ՄԵԾՆ ԷՐԻԿ","ՄԵԾՆ-ԷՐԻԿ"],"high",
  "Site terms: operated by «Braverk» ՍՊԸ, formerly known as «Metsn Erik» ՍՊԸ; address Arshakunyats Ave 67/15. Rebranded May 2026 after 31 years; roots in Shirak-95 (Gyumri, 1995), led by Levon Shahumyan. Exact Armenian spelling of old name (Մեծն Էրիկ) inferred from transliteration. Projects: AR23 Residence, Alma-Ata Residence, Riga House; also public infrastructure & restoration works.",
  pos=[{"title":"31-year construction track record incl. public infrastructure and restoration","url":"https://brawerk.am/en/news/rebranding-metsn-erik-is-now-brawerk","summary":"Company history since 1995 (Shirak-95 → Metsn Erik → Brawerk)."}],founded=1995))
json.dump(out,open('research_D.json','w'),ensure_ascii=False,indent=1)
print(len(out))
out[0]["news_issues"].append({"date":"2024-10-23","title":"Komitas State Conservatory students: roof renovation by Bedeck missed 28 Aug 2024 deadline, rain damaged floors","url":"https://168.am/2024/10/23/2114843.html","summary":"Public-works delay complaint against Bedeck (contract with Education Ministry / Urban Development Committee)."})
out[1]["news_issues"]=out[0]["news_issues"]
for r in out[:2]:
    r["legal_entities"][-1]["tax_id"]="00450801"; r["legal_entities"][-1]["source_url"]="https://www.construction.am/arm/companies/bedeck/"
out[1]["notes"]+=" Pars' phone +374 11 575522 equals Bedeck's office phone on construction.am (Sasuntsi Davit 87) - confirms link. Bedeck TIN 00450801."
out[1]["datalex_names"]=["ՊԱՐՍ","ԲԻԴԵՔ"]
out[2]["legal_entities"][0]["registered_year"]=2023; out[2]["founded_year"]=2023
out[2]["notes"]+=" construction.am: founded 2023, general contractor (concrete pumping, heavy machinery)."
ARGO="ARGO Realty (ar-go.am, Komitas 19/1, phone +374 55 200707, founded ~2009) is the SALES AGENT; the +374 55 200707 phone in our data belongs to ARGO, not the developer. ARGO's partner list includes this LLC among many ARGO-marketed developers (1SQ-ARGO, Mitstart, Man Invest Group...), so common ownership with ARGO is possible but unproven."
out.append(R("Em Es Grup","developer",[E("«ԷՄ ԷՍ ԳՐՈՒՊ» ՍՊԸ","EM ES GROUP LLC",src="https://ar-go.am/project/babajanyan"),E("SAM KAR SHIN (contractor)","Sam Kar Shin",src="https://ar-go.am/project/babajanyan")],["ԷՄ ԷՍ ԳՐՈՒՊ","ՍԱՄ ԿԱՌ ՇԻՆ","ՍԱՄԿԱՌՇԻՆ","ՍԱՄ-ԿԱՌ-ՇԻՆ"],"high",
  "Babajanyan complex (Arinj, P. Sevak 17th st, 17 floors, 170 apts): developer «ԷՄ ԷՍ ԳՐՈՒՊ» ՍՊԸ, builder SAM KAR SHIN (Armenian spelling of contractor guessed), bank ACBA. "+ARGO+" No news found (site searches azatutyun/armlur/168/factor/aravot)."))
manents=[E("«ՄԱՆ ԻՆՎԵՍՏ ԳՐՈՒՊ» ՍՊԸ","MAN INVEST GROUP LLC",src="https://www.evoca.am/hy/construction-companies")]
manpos=[{"title":"Drsum (phase 1) residential district in Kanakeravan: 10 low-rise buildings, ~400 apts; Drsum 2 (337 apts) started 2026 with Evocabank","url":"https://ar-go.am/project/drsoom-bnakeli-hamalir-1","summary":"Developer and builder is MAN INVEST GROUP itself; ar-go lists permit and acceptance-act documents."}]
for dev in ["Man Invest Grup","MAN INVEST GROUP"]:
    out.append(R(dev,"developer",manents,["ՄԱՆ ԻՆՎԵՍՏ ԳՐՈՒՊ"],"high",
      "Same company under two display names ('Man Invest Grup' from ar-go.am, 'MAN INVEST GROUP' from evoca.am). Evoca lists «ՄԱՆ ԻՆՎԵՍՏ ԳՐՈՒՊ» ՍՊԸ as developer & builder at Yerevanyan hwy 6/8, Kanakeravan (Nor Hachn). Name already queued in queue_main (not repeated). "+ARGO+" Possibly related to 'Man Group' LLC (construction.am, founded 2012, Vahe Ohanjanyan) - unverified, not queued. No negative news found.",pos=manpos))
out.append(R("Best Propertis","developer",[E("«ԲԵՍԹ ՓՐՈՓԵՐԹԻՍ» ՍՊԸ","BEST PROPERTIES LLC",src="https://ar-go.am/project/halabyan751"),E("«ԼԱՍ ԿՈ» ՍՊԸ (contractor)","LAS KO LLC",src="https://ar-go.am/project/halabyan751")],["ԲԵՍԹ ՓՐՈՓԵՐԹԻՍ","ԼԱՍ ԿՈ","ԼԱՍ-ԿՈ"],"high",
  "Halabyan 75/1 (Ajapnyak, 256 apts, 188 parking, completed, all apartments sold): developer «ԲԵՍԹ ՓՐՈՓԵՐԹԻՍ» ՍՊԸ, builder «ԼԱՍ ԿՈ» ՍՊԸ, bank Converse Bank. "+ARGO+" No news found.",
  pos=[{"title":"Halabyan 75/1 completed with acceptance act; all apartments sold","url":"https://ar-go.am/project/halabyan751","summary":"256-apartment completed complex."}]))
out.append(R("Nor Hachn Hills","developer",[E("«ՆՈՐ ՀԱՃՆ ՀԻԼԼՍ» ՍՊԸ","NOR HACHN HILLS LLC",src="https://ar-go.am/project/nor-hatchn-hills"),E("«ՄԻԴԻՍ ՔՈՆՍԹՐԱՔՇՆ» ՍՊԸ (contractor)","Midis Construction LLC",src="https://ar-go.am/project/nor-hatchn-hills")],["ՆՈՐ ՀԱՃՆ ՀԻԼԼՍ","ՄԻԴԻՍ ՔՈՆՍԹՐԱՔՇՆ","ՄԻԴԻՍ ԿՈՆՍՏՐՈՒԿՑԻԱ"],"high",
  "Project-specific LLC; 420 apts at Z. Andranik 8/3 Nor Hachn, start 01.08.2026, end 01.08.2029, builder «ՄԻԴԻՍ ՔՈՆՍԹՐԱՔՇՆ» ՍՊԸ (Midis Construction; marketed also by Silver Real Estate). Newly started - no track record for the SPV. "+ARGO+" No news found."))
out.append(R("Living Rezidens","developer",[E("«ԼԻՎԻՆԳ ՌԵԶԻԴԵՆՍ» ՍՊԸ","LIVING RESIDENCE LLC",src="https://ar-go.am/project/tevosyan13")],["ԼԻՎԻՆԳ ՌԵԶԻԴԵՆՍ"],"high",
  "Tevosyan 1/3 (Nor Nork 4th block, 2 buildings, 315 apts): developer and builder «ԼԻՎԻՆԳ ՌԵԶԻԴԵՆՍ» ՍՊԸ, bank ACBA; started Sept 2022, marked completed with acceptance act. "+ARGO+" No news found.",
  pos=[{"title":"Tevosyan 1/3 (315 apts) completed, acceptance act published","url":"https://ar-go.am/project/tevosyan13","summary":"Completed ~3 years after start."}]))
out.append(R("CRAFTED CONSTRUCTIONS","developer",[E("«ՔՐԱՖԹԻԴ ՔՈՆՍԹՐԱՔՇՆՍ» ՍՊԸ","CRAFTED CONSTRUCTIONS LLC",src="https://ar-go.am/project/gyurjyan-gallery-bnakeli-hamalir"),E("«ՄԻԹՍԹԱՐԹ» ՍՊԸ","MITSTART LLC",src="https://ar-go.am/project/gyurjyan-gallery-bnakeli-hamalir"),E("«Դ ԵՎ Ս ՔՈՆՍԹՐԱՔՇՆ» ՍՊԸ (contractor)","D and S Construction LLC",src="https://ar-go.am/project/gyurjyan-gallery-bnakeli-hamalir")],["ՔՐԱՖԹԻԴ ՔՈՆՍԹՐԱՔՇՆՍ","ՄԻԹՍԹԱՐԹ","Դ ԵՎ Ս ՔՈՆՍԹՐԱՔՇՆ","Դ ԵՎ Ս ԿՈՆՍՏՐՈՒԿՑԻԱ"],"medium",
  "Gyurjyan Gallery (Gyurjyan 14/6, Nor Nork, 50 apts, 2025-03-06 to 2027-03-06): ar-go.am page header lists developer «ՄԻԹՍԹԱՐԹ» ՍՊԸ while the description says developer «ՔՐԱՖԹԻԴ ՔՈՆՍԹՐԱՔՇՆՍ» ՍՊԸ, builder «Դ ԵՎ Ս ՔՈՆՍԹՐԱՔՇՆ» ՍՊԸ, bank Ameriabank. Mitstart LLC is also an Evoca partner developer (Zovuni, Nairi) with ARGO's phone - likely an ARGO-affiliated developer; roles between the two LLCs unclear, both queued. "+ARGO+" No news found."))
out.append(R("Dream Ston","developer",[E("«Դրեամ Սթոն» ՍՊԸ (as spelled in ACBA list; likely registered «ԴՐԻՄ ՍԹՈՆ ...»)","Dream Stone LLC",src="https://www.acba.am/hy/individuals/loans/mortgage/constructors#11023")],["ԴՐԻՄ ՍԹՈՆ ՌԵԶԻԴԵՆՍ","ԴՐԻՄ ՍԹՈՈՒՆ ՌԵԶԻԴԵՆՍ","ԴՐԻՄ ՍԹՈՆ","ԴՐԵԱՄ ՍԹՈՆ","ԴՐԵԱՄ ՍԹՈՆ ՌԵԶԻԴԵՆՍ"],"low",
  "ACBA constructor list (our scrape) names the developer 'Դրեամ Սթոն ՍՊԸ' for 'ԴՐԻՄ ՍԹՈՆ ՌԵԶԻԴԵՆՍ' (Arshakunyats 1st lane 36, Kentron, 11 floors, 50 apts, commissioning 30.06.2026, 1,000,000 AMD/m2, contact r.eghiazaryann@mail.ru). Also marketed by redgroup.am as 'Դրիմ Սթոուն Ռեզիդենս' (next to SAS supermarket). Exact registered spelling unknown (ԴՐԵԱՄ vs ԴՐԻՄ, ՍԹՈՆ vs ՍԹՈՈՒՆ) - several variants queued. No news found; WebSearch budget exhausted during research so coverage limited."))
out.append(R("V.v.b","developer",[E("«Վ.Վ.Բ» ՍՊԸ","V.V.B LLC",src="https://www.acba.am/hy/individuals/loans/mortgage/constructors#10491")],["Վ.Վ.Բ","ՎՎԲ"],"medium",
  "ACBA partner list: developer «Վ.Վ.Բ» ՍՊԸ for 'ՎՎ8 Ռեզիդենս', Vagharshyan St 8, Arabkir (8 floors, 26 apts, commissioning 29.12.2028), contact kkasaryan@icloud.com. Names already queued in queue_main. Abbreviated name - datalex matches may include namesakes. No news found (address search returned only unrelated Vagharshyan St items)."))
out.append(R("Armstroy Proyekt","developer",[E("«Արմստրոյ Պրոյեկտ» ՍՊԸ","Armstroy Project LLC",src="https://www.acba.am/hy/individuals/loans/mortgage/constructors#10187")],["ԱՐՄՍՏՐՈՅ ՊՐՈՅԵԿՏ"],"medium",
  "ACBA partner list: «Արմստրոյ Պրոյեկտ» ՍՊԸ, Arghutyan 10/15 Arabkir, 14 floors, 81 apts; commissioning date 06.12.2025 listed while still 'under construction' - verify whether it is overdue. Name already queued in queue_main. No news found.",
  issues=[]))
out.append(R("Parklife Eco Residency","developer",[E("Parklife Eco Residency (Պարկլայֆ Էկո Ռեզիդենսի) - legal form/spelling unconfirmed","Parklife Eco Residency",form="unknown",src="https://www.construction.am/arm/companies/parklife-eco-residency/",yr=2021)],["ՊԱՐԿԼԱՅՖ ԷԿՈ ՌԵԶԻԴԵՆՍ","ՓԱՐՔԼԱՅՖ ԷԿՈ ՌԵԶԻԴԵՆՍ","ՊԱՐԿԼԱՅՖ"],"low",
  "Website (parklife.am, by WEDO) discloses no legal entity. construction.am profile 'Պարկլայֆ Էկո Ռեզիդենսի', founded 2021, office Komitas Ave 56, phone 33 925555. 20 ha, 107 private houses + apartment buildings at Bagrevand 84, Nor Nork. Registered LLC name may differ (land owner/investor unknown). No news found.",founded=2021))
out.append(R("KASAKHUM","developer",[E("«Մովսեսյան ընդ Փարթներս Քոնսթրաքշն» (Movsesyan & Partners Construction) - form unconfirmed","Movsesyan & Partners Construction",form="ՍՊԸ?",src="https://www.construction.am/arm/companies/movsesyan-and-partners/",yr=2019),E("ՔԱՍԱԽՈՒՄ (myhome.am developer label; project brand, possibly SPV)","Kasakhum",form="unknown",src="https://myhome.am/en/building/266")],["ՔԱՍԱԽՈՒՄ","ՄՈՎՍԵՍՅԱՆ ԵՎ ԳՈՐԾԸՆԿԵՐՆԵՐ","ՄՈՎՍԵՍՅԱՆ ԸՆԴ ՓԱՐԹՆԵՐՍ","ՄՈՎՍԵՍՅԱՆ ԸՆԴ ՓԱՐԹՆԵՐՍ ՔՈՆՍԹՐԱՔՇՆ"],"medium",
  "myhome.am developer 'ՔԱՍԱԽՈՒՄ' for Kasakh project (V. Teryan 3rd st plot 32, 28 apts) with website/email/phone of Movsesyan & Partners; construction.am: Movsesyan & Partners Construction founded 2019, head Vardan Movsesyan, Komitas 23/3, phone 55 224746 (same as project). Same brand also markets Caveman Residence, Dilijan Inn, Orjonikidze 83/1. 'ՔԱՍԱԽՈՒՄ' may also match news/court texts about Kasakh village ('in Kasakh') - treat datalex hits carefully. No developer-specific news found.",founded=2019))
out.append(R("Micro-district 318","unknown",[E("unknown (myhome.am label 'Միկրոշրջան 318')","Micro-district 318",form="unknown",src="https://myhome.am/en/building/230")],["ՄԻԿՐՈՇՐՋԱՆ 318","ՄԻԿՐՈՇՐՋԱՆ-318"],"low",
  "Only source is myhome.am (Ameriabank partner): 48 apts, T. Manukyan 318 Hrazdan, contact shahen_hakobjanyan@mail.ru (suggests person Shahen Hakobjanyan). Legal entity not identified; queued name is the project label and likely will not match a registry name."))
out.append(R("White island","developer",[E("«White island» ՍՊԸ (Armenian registered spelling unknown)","White Island LLC",src="https://www.evoca.am/hy/construction-companies")],["ՎԱՅԹ ԱՅԼԵՆԴ","ՈՒԱՅԹ ԱՅԼԵՆԴ","WHITE ISLAND"],"low",
  "Evoca developer list: «White island» ՍՊԸ, Ashtarak, phones 091 767606 / 091 473874. No project page, website or news found; Armenian spelling guessed."))
out.append(R("In Town","developer",[E("In Town (legal entity not stated)","In Town",form="unknown",src="https://www.evoca.am/hy/construction-companies"),E("«ՊՐԵՄԻՈՒՄ ՌԻԵԼԹԻ» (sales agent)","Premium Realty",src="https://www.evoca.am/hy/construction-companies")],["ԻՆ ԹԱՈՒՆ","ԻՆ-ԹԱՈՒՆ","ՊՐԵՄԻՈՒՄ ՌԻԵԼԹԻ"],"low",
  "Evoca: builder 'In Town', Lchapi St 1/3 Dzoraghbyur (Jrvezh), sales manager «ՊՐԵՄԻՈՒՄ ՌԻԵԼԹԻ», phone 096 032303 (agent's). Developer LLC not identified; 'In Town' is probably a project brand. Agent name queued as a secondary lead."))
out.append(R("S.K. Group","developer",[E("«Ս.Կ. ԳՐՈՒՊ» ՍՊԸ","S.K. Group LLC",src="https://www.evoca.am/hy/construction-companies"),E("«Շինարտ Գրուպ» ՍՊԸ (related: same phone)","Shinart Group LLC",tax="00921868",yr=2019,src="https://www.construction.am/arm/companies/shinart-group/")],["Ս.Կ. ԳՐՈՒՊ","ՍԿ ԳՐՈՒՊ","ԷՍ ՔԵՅ ԳՐՈՒՊ","ՇԻՆԱՐՏ ԳՐՈՒՊ"],"medium",
  "Evoca: «Ս.Կ. ԳՐՈՒՊ» ՍՊԸ, office Leningradyan 27/6 Malatia, phone +374 33 400410 - identical to «Շինարտ Գրուպ» ՍՊԸ (Nazarbekyan 41/1; TIN 00921868, founded 2019 per construction.am), so the two are likely affiliated (same group) - affiliation inferred from phone only.",
  issues=[{"date":"2025-07-02","title":"Azatutyun: buyer sues developer Shinart Group over >1-year late handover; company counter-sued a group of buyers to annul contracts","url":"https://www.azatutyun.am/a/kaghakatsin-dati-e-tvel-karoutsapatogh-ynkeroutyany-verjins-el-nran-ev-ayl-bnakichneri/33461119.html","summary":"Buyer says permit extension to July 2024 was obtained 3 days before signing but not disclosed; building finished Sept 2024. Shinart Group says ~85% of buyers settled, and it filed counter-claims against buyers who sued (applies to related company Shinart Group, not directly S.K. Group)."}]))
out.append(R("SV & GA","developer",[E("«ՍՎ ԵՎ ԳԱ» ՍՊԸ","SV & GA LLC",src="https://www.evoca.am/hy/construction-companies")],["ՍՎ ԵՎ ԳԱ","ԷՍ ՎԻ ԷՆԴ ՋԻ ԷՅ"],"medium",
  "Evoca (hy): «ՍՎ ԵՎ ԳԱ» ՍՊԸ, G. Ghapantsyan 3 Arabkir, phone 044 777909, website art-group.am. art-group.am is 'Art Group LLC', an IT/infrastructure integrator (Adobe/APC partner) - relationship (common owner) presumed but unverified; 'ԱՐՏ ԳՐՈՒՊ' not queued as too generic. No news found."))
out.append(R("Imperial Construction","developer",[E("«Իմպերիալ Քոնսթրաքշն» ՍՊԸ","Imperial Construction LLC",src="https://www.evoca.am/hy/construction-companies")],["ԻՄՊԵՐԻԱԼ ՔՈՆՍԹՐԱՔՇՆ","ԻՄՊԵՐԻԱԼ ԿՈՆՍՏՐՈՒԿՑԻԱ"],"medium",
  "Evoca (hy): 'Իմպերիալ Քոնսթրաքշն ՍՊԸ', N. Gogol 24/23 (Kanaker-Zeytun). No phone/website/project details; no news found."))
order=[d["developer"] for d in json.load(open('group_D.json'))]
byd={r["developer"]:r for r in out}
missing=[d for d in order if d not in byd]
print("missing",missing)
json.dump([byd[d] for d in order if d in byd],open('research_D.json','w'),ensure_ascii=False,indent=1)
print(len(byd))
