import sys; sys.path.insert(0,'.')
from mk import *
dev="Capital Build"; du="https://www.capitalbuild.am/"; ph=["+37444610109","+37412610109"]; em="capital.buildinfo@gmail.com"
so={"facebook":"https://www.facebook.com/capital.build.estate","instagram":"https://www.instagram.com/capital_build_estate/","youtube":"https://www.youtube.com/channel/UCsShRGwnVQMErC5HyWg1Smw"}
S="https://www.capitalbuild.am/storage/files/"; B="https://www.capitalbuild.am/en/projects/project/"
def R(slug,**k):
    k.setdefault("source_url",B+slug)
    return rec(developer=dev,developer_url=du,phones=ph,email=em,social=so,**k)
P=[R("white-sky-residence",title="White Sky Residence",city="Yerevan",district="Davtashen",address="Next to Davtashen Bridge, Davtashen, Yerevan",price_min_amd_m2=550000,price_currency_raw="550000 (AMD/m2, projects list)",status="under construction",floors="21,25,31",type="residential",
  images=[S+"img-7392.jpg",S+"img-7390.jpg",S+"img-7391.jpg",S+"img-6924.jpg",S+"img-6955.jpg",S+"img-6925.jpg",S+"img-7394.jpg"],
  description="New high-rise complex in Davtashen next to the Davtashen Bridge: 3 towers of 21, 25 and 31 floors with 704 apartments from 45 m2, unobstructed views in all directions, landscaped courtyard, 4-level underground parking, seismic resistance, contemporary architecture. Sales open; from 550,000 AMD/m2."),
 R("malibu-park",title="Malibu Park",city="Yerevan",district="Kentron",address="16 Ekmalyan Lane, Yerevan",lat=40.184644,lng=44.508442,status="under construction",type="mixed",
  images=[S+"img-4599.png",S+"img-4586.png",S+"img-4601.png",S+"img-4597.png",S+"img-4589.png",S+"img-4592.png",S+"img-4571.png",S+"img-4547.png"],
  description="Next-generation luxury complex of 2 buildings in Kentron next to Seasons Park, walking distance to Republic Square, Opera and Northern Avenue. Signature-designed common areas and relaxation zones, commercial spaces, 3-level underground parking, valet parking, 24/7 security, doorman/concierge; apartments offered with high-quality finishing and furnishing. Construction in full progress."),
 R("arshakounyac-rezidens",title="Arshakunyats Residence",source_url="https://www.capitalbuild.am/projects/project/arshakounyac-rezidens",city="Yerevan",district="Kentron",address="12 Sevan St, Yerevan",lat=40.162756,lng=44.507792,price_min_amd_m2=900000,price_currency_raw="1 m2 from 900000 AMD; income tax refund",status="under construction",floors="24",type="mixed",
  images=[S+"untitled-1-3.jpg",S+"1_26.jpg"],
  description="Premium complex in Kentron at Sevan St 12, 1 km from Republic Square: three 24-storey buildings with 987 apartments, fully glazed facades with rounded edges and sky bridges, 3-level underground parking and 3 floors of public/commercial space; seismic resistant. From 900,000 AMD/m2; income-tax mortgage refund."),
 R("blue-sky-residence",title="Blue Sky Residence",city="Yerevan",district="Davtashen",address="7/6 Pirumyanner St, Davtashen, Yerevan",lat=40.222487,lng=44.491634,price_min_amd_m2=620000,price_currency_raw="1 m2 from 620000 AMD (last apartments); income tax refund",status="under construction",floors="18",type="residential",
  images=[S+"untitled-6.png",S+"ssss-1180x_.jpg",S+"img-6869.png",S+"img-6970.png",S+"img-6855.jpg",S+"img-6968.png",S+"img-6854.jpg"],
  description="Premium family complex in Davtashen: 18 above-ground + 4 underground floors, 265 apartments and 13 penthouses, ceiling height 3.10 m, white travertine and black tuff cladding, aluminium windows; 4-level parking, enclosed car-free courtyard, 24/7 security. Delivered with partitions, levelled floors and plastered walls. Last apartments from 620,000 AMD/m2."),
 R("avenyou-22",title="Avenue 22",source_url="https://www.capitalbuild.am/projects/project/avenyou-22",city="Yerevan",district="Nor Nork",address="22 Dro St, Yerevan",lat=40.205271,lng=44.544765,price_min_amd_m2=600000,price_currency_raw="1 m2 from 600000 AMD (last apartments)",status="under construction",floors="18,22",type="mixed",
  images=[S+"glxavor-1_1.jpg",S+"glxavor-1_2.jpg"],
  description="Multifunctional complex at Dro St 22: three buildings (two 22-storey, one 18-storey) with 614 apartments, 3-level underground parking, offices, shops and services, 5,200 m2 of green areas with playgrounds and rest zones, centralized eco-friendly heating, energy-saving sun-protective glazing, ventilated facade. Last apartments from 600,000 AMD/m2."),
 R("bestland",title="Bestland Residence",city="Dzoraghbyur",district="Kotayk",address="Greenland district, Dzoraghbyur (Jrvezh), Kotayk",lat=40.195111,lng=44.610037,price_min_amd_m2=550000,price_currency_raw="1 m2 from 550000 AMD (last townhouses)",status="under construction",floors="2-3",type="residential",
  images=[S+"glkhavvor.jpg",S+"glkhavvor_1.jpg",S+"glkhavvor_2.jpg",S+"01_1.jpg",S+"02-2.jpg",S+"04-1.jpg",S+"05_1.jpg"],
  description="Townhouse community near Yerevan: 70 individual 2-3 storey houses of 105.8-256.8 m2, each with its own garage, individual heating; 28,524 m2 site with 60% unfenced landscaped greenery, views of Aragats and Ararat; own pump station, substation and gas; shop, cafe, open-air pool and playground. Last townhouses from 550,000 AMD/m2.",
  apartments=[{"rooms":"townhouse","area_min":105.8,"area_max":256.8,"price_from":None,"currency":None}]),
 R("caghkadzor-v-haroutyounyan-2-10",source_url="https://www.capitalbuild.am/projects/project/caghkadzor-v-haroutyounyan-2-10",title="Tsaghkadzor 2/10",city="Tsaghkadzor",district="Kotayk",address="2/10 V. Harutyunyan St, Tsaghkadzor",lat=40.533786,lng=44.712965,price_currency_raw="All apartments sold",status="completed",floors="4,5,7,9",type="resort",
  images=[S+"01-1.jpg",S+"01-1_1.jpg",S+"02-1.jpg",S+"04-1_1.jpg",S+"tsaghkadzvorvharvouthyvounyan-6.png"],
  description="Multifunctional residential complex in Tsaghkadzor: 275 apartments in 4 buildings (A 5 floors, B 9-storey terraced, C 4 floors, D 7 floors) over one-level underground parking; 3-storey semi-underground spa centre and fitness hall between A and B, outdoor swimming pool. All apartments sold."),
 R("caghkadzor-v-haroutyounyan-6",source_url="https://www.capitalbuild.am/projects/project/caghkadzor-v-haroutyounyan-6",title="Tsaghkadzor 6",city="Tsaghkadzor",district="Kotayk",address="6 V. Harutyunyan St, Tsaghkadzor",lat=40.5328,lng=44.721561,price_currency_raw="Coming soon",status="planned",type="resort",
  images=[S+"taxkador-new-main-slide.jpg"],description="Upcoming Capital Build complex in Tsaghkadzor at V. Harutyunyan 6: 314 apartments, 220 parking spaces, 3-4 buildings. Coming soon."),
 R("davtashen-arajin-taghamas-11-2",source_url="https://www.capitalbuild.am/projects/project/davtashen-arajin-taghamas-11-2",title="Davtashen 11/2",city="Yerevan",district="Davtashen",address="Davtashen 1st district, 11/2, Yerevan",lat=40.222193,lng=44.488293,price_currency_raw="All apartments sold",status="completed",type="residential",
  images=[S+"3_4.jpg",S+"4_3.jpg",S+"davtashen-4-1.jpg",S+"davtashen-8.jpg"],description="Residential building with 108 apartments and 28 parking spaces in Davtashen 1st district, delivered fully renovated; passenger and freight lifts, green areas, playgrounds, security systems. Sold out."),
 R("davtashen-arajin-taghamas-61",source_url="https://www.capitalbuild.am/projects/project/davtashen-arajin-taghamas-61",title="Davtashen 61",city="Yerevan",district="Davtashen",address="Davtashen 1st district, 61, Yerevan",lat=40.220556,lng=44.478852,price_currency_raw="All apartments sold",status="completed",floors="13",type="residential",
  images=[S+"01_3.jpg",S+"02_1.jpg",S+"03-1.jpg",S+"08_1.jpg",S+"davtashen_1.png"],description="13 above-ground + 2 underground floor building with 86 apartments and 61 parking spaces in Davtashen, green area and playground, passenger and freight lifts, security system. Sold out."),
 R("komitas-19-1",title="Komitas 19/1",city="Yerevan",district="Arabkir",address="19/1 Komitas Ave, Yerevan",lat=40.203864,lng=44.500464,price_currency_raw="Sold out",status="completed",type="residential",
  images=[S+"komitas-19-1.jpg",S+"komitas-19-2.jpg",S+"komitas-19-3.jpg",S+"komitas-19-4.jpg"],description="Residential building at Komitas 19/1 with 46 apartments and 22 parking spaces. Sold out."),
 R("a-xachatryan-3",source_url="https://www.capitalbuild.am/projects/project/a-xachatryan-3",title="A. Khachatryan 3",city="Yerevan",district="Arabkir",address="3 Aram Khachatryan St, Yerevan",lat=40.203291,lng=44.491081,price_currency_raw="All apartments sold",status="completed",type="residential",
  images=[S+"1_4.jpg",S+"aram-khachatryan-1.jpg",S+"aram-khachatryan-2.jpg",S+"aram-khachatryan-3.jpg",S+"aram-khachatryan.png"],description="Residential complex on A. Khachatryan St with 212+ apartments and 170+ parking spaces, oriented for natural light and views, good road access and infrastructure. Sold out."),
 R("project-1",title="Komitas 59",city="Yerevan",district="Arabkir",address="59 Komitas Ave, Yerevan",lat=40.206802,lng=44.521681,price_currency_raw="Sold out",status="completed",type="mixed",
  images=[S+"1.jpg",S+"2.jpg",S+"3.jpg",S+"b-8-6_2.jpg"],description="Multifunctional complex of 3 buildings (A, B, C) with 763 apartments and 3-level underground parking; offices, shops, cafes, laundry, spa, gym, kindergarten; 9,000 m2 green areas and playgrounds. Sold out.")]
save("10_capitalbuild",P)
